<?php
echo "<pre>";
print_r($contestDetails);
print_r($contestPhotos);
?>

<div class="container">
    <div class="row">

        <div class="col-lg-12">
            <h1 class="page-header">Thumbnail Gallery</h1>
        </div>

        <?php foreach($contestPhotos as $photo) { ?>
        
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail">
                <img class="img-responsive" src="<?php echo $this->basePath('/img/contest/thumbnail/' . $photo['thumbnail']); ?>" alt="<?php echo $photo['thumbnail']; ?>">
            </a>
        </div>
            
        <?php } ?>
    </div>
</div>