<div class="jumbotron">
    <div class="row">

        <div class="col-lg-12">
            <h1 class="page-header">Thumbnail Gallery</h1>
        </div>

        <?php 
        if(empty($contestPhotos)) {
            echo "No photos uploaded to contest yet.";            
        } else {
            foreach ($contestPhotos as $photo) { ?>

                <div class="col-lg-2 col-md-3 col-xs-4 thumb">
                    <img class="img-responsive" src="<?php echo $this->mediaImage($photo, 'icons'); ?>" alt="<?php echo $photo['filename']; ?>">
                    <br>
                    <button media_id="<?php echo $photo['media_id']; ?>" contest_id="<?php echo $photo['contest_id']; ?>" type="button" class="btn btn-danger center-block remove">Remove</button>
                </div>
            <?php } 
        }?>
            
    </div>
</div>
<script>

    $('.remove').click(function () {
        if (confirm("Do you want to remove this photo from the contest ?")) {
            $.ajax({
                url: '<?php echo $this->basePath('/manager/delete-contest-media'); ?>',
                type: 'POST',
                data: 'contest_id=' + $(this).attr('contest_id') + '&media_id=' + $(this).attr('media_id'),
                success: function (response) {
                    bootbox.alert(response.message, function () {
                        if (response.success) {
                            location.reload();
                        }
                    });
                }
            });
        }
        return false;
    });
</script>