<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/library/metronic/template/assets/plugins/bootstrap-datepicker/css/datepicker.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/library/metronic/template/assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/library/metronic/template/assets/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css'); ?>">
<style>
    table>tbody>tr>td, table>thead>tr>th {
        vertical-align: middle !important;
        text-align: center !important;
    }
    .help-block {
        margin-bottom: auto !important;
        font-size: inherit !important;
        font-weight: inherit !important;
    }
</style>
<!-- END PAGE LEVEL STYLES -->

<div class="jumbotron">
    <a class="pull-left" href="<?php echo $this->config('admin_main_site', 'url') ?>">
        <i class="fa fa-backward"></i> Go to main site
    </a>
    <?php
    if ($is_reviewer) {
        //don't show create contest
    } else {
        ?>
        <a class="btn btn-primary pull-right open-modal" data-toggle="modal" href="#create-contest-modal">
            Create Contest
        </a>
    <?php } ?>

    <div class="portlet">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-trophy"></i>Contests
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-advance table-hover">
                    <thead>
                        <tr>                            
                            <th>
                                <i class="fa fa-picture-o"></i> Thumbnail
                            </th>
                            <th>
                                <i class="fa"></i> Name
                            </th>
                            <th class="hidden-xs">
                                Entry End Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-calendar"></i> Voting Start Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-calendar"></i> Winners Announce Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-group"></i> Entries Limit
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-star"></i> Exclusive
                            </th>
                            <th>
                                <i class="fa"></i> Type
                            </th>
                            <?php
                            if ($is_reviewer) {
                                //don't show create contest
                            } else {
                                ?><th>
                                </th>
                            <?php } ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($contests as $contest) { ?>
                            <tr>
                                <td>                                    
                                    <img src="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>" alt="Image not available" style="width:100px" />
                                </td>
                                <td class="highlight">
                                    <a class="name" contest_id="<?php echo $contest['id']; ?>">
                                        <?php echo $contest['name']; ?>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $contest['entry_end_date']; ?>
                                </td>
                                <td>
                                    <?php echo $contest['voting_start_date']; ?>
                                </td>
                                <td>
                                    <?php echo $contest['winners_announce_date']; ?>
                                </td>
                                <td>
                                    <?php echo $contest['max_no_of_photos']; ?>
                                </td>
                                <td>
                                    <?php echo $contest['is_exclusive'] ? 'YES' : 'NO'; ?>
                                </td>
                                <td>
                                    <?php echo $contest['type']; ?>
                                </td>
                                <?php
                                if ($is_reviewer) {
                                    //don't show create contest
                                } else {
                                    ?>
                                    <td>
                                        <a contest_id="<?php echo $contest['id']; ?>" class="btn default btn-xs purple edit">
                                            <i class="fa fa-edit"></i> Edit
                                        </a>
                                        <a contest_id="<?php echo $contest['id']; ?>" class="btn default btn-xs red delete">
                                            <i class="fa fa-trash-o"></i> Delete
                                        </a>
                                    </td>
                                <?php } ?>
                            </tr>
                        <?php } ?>                        
                    </tbody>
                </table>
            </div>
            <div>
                <ul class="pagination pull-right">
                    <li>
                        <?php if ($totalPages > 1) { ?>
                            <a class="page-number" value="<?php echo $currentPage == 1 ? $totalPages : $currentPage - 1; ?>">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        </li>
                        <?php for ($i = 1; $i <= $totalPages; $i++) { ?>
                            <li>
                                <a class="page-number" value="<?php echo $i; ?>">
                                    <?php echo $i; ?>
                                </a>
                            </li>
                        <?php } ?>
                        <li>
                            <a class="page-number" value="<?php echo $currentPage == $totalPages ? 1 : $currentPage + 1; ?>">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        <?php } ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="modal fade" id="create-contest-modal" role="basic" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" style="width: 750px !important">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12 ">
                            <!-- BEGIN CREATE CONTEST FORM-->
                            <div class="portlet">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-reorder"></i> Create Contest

                                    </div>                
                                    <div class="tools">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                    </div>
                                </div>
                                <div class="portlet-body form">
                                    <form action="#" role="form" id="create-contest-form">
                                        <div class="form-body">
                                            <div class="alert alert-danger display-hide">
                                                <button class="close" data-close="alert"></button>
                                                You have some form errors. Please check below.
                                            </div>
                                            <div class="alert alert-success display-hide">
                                                <button class="close" data-close="alert"></button>
                                                Your form validation is successful!
                                            </div>
                                            <div class="form-group hidden">
                                                <input type="text" id="id" name="id" value='0'>
                                            </div>                        
                                            <div class="form-group col-md-12">
                                                <label class="control-label" for="name">
                                                    Contest Name
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <input type="text" data-required="1" class="form-control" id="name" name="name" placeholder="Enter Contest's Name">
                                            </div>                        
                                            <div class="form-group col-md-12">
                                                <label class="control-label" for="description">
                                                    Contest Description
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <textarea class="wysihtml5 form-control" id="description" name="description" rows="3" placeholder="Enter Contest's Description"></textarea>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <label class="control-label" for="thumbnail">
                                                    Thumbnail
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <input type="file" id="thumbnail" name="thumbnail">
                                                <input type="text" class="form-control" disabled hidden id="thumbnail_name">
                                                <p class="help-block">Upload a square resolution image(For best appearance-Minimum Resolution: 300px X 300px)</p>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="entryEndDate">
                                                    Entry End Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
                                                    <input id="entryEndDate" name="entryEndDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="winnersAnnounceDate">
                                                    Winners Announce Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
                                                    <input id="winnersAnnounceDate" name="winnersAnnounceDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>                                            
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="votingStartDate">
                                                    Voting Start Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
                                                    <input id="votingStartDate" name="votingStartDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="entryLimit">
                                                    Entries Limit
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <input type="number" data-required="1" class="form-control" id="entryLimit" name="entryLimit" placeholder="Enter Contest's Entries Limit">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="type">
                                                    Contest Type
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <select class="form-control" id="type" name="type">
                                                    <?php foreach ($types as $type) { ?>
                                                        <option value="<?php echo $type['id']; ?>"><?php echo $type['type'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label>Is Exclusive Contest?</label>
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <div class="radio"><span><input type="radio" name="exclusive" id="exclusive-yes" value="1"></span></div> Yes </label>
                                                    <label class="radio-inline">
                                                        <div class="radio"><span><input type="radio" name="exclusive" id="exclusive-no" value="0" checked=""></span></div> No </label>
                                                </div>
                                            </div>
                                            <div class="form-actions col-md-12">
                                                <button type="submit" class="btn blue">Submit</button>
                                                <button type="button" class="btn default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                            </div>
                                    </form>
                                </div>
                            </div>
                            <!-- END CREATE CONTEST FORM-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL SCRIPTS -->

<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('library/metronic/template/assets/scripts/custom/components-pickers.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js'); ?>"></script>
<script src="<?php echo $this->basePath('library/metronic/template/assets/scripts/custom/components-editors.js'); ?>"></script>

<!-- END PAGE LEVEL PLUGINS -->
<script>

    $(document).ready(function () {
        App.init();
        ComponentsPickers.init();
        ComponentsEditors.init();
        //handleValidation();
        $('.open-modal').click(function () {
            $("input[name='exclusive'][value=1]").parent().removeClass('checked');
            $("input[name='exclusive'][value=0]").parent().addClass('checked');
            $('form#create-contest-form').trigger('reset');
            $('#thumbnail_name').hide();
        });

        $('.name').click(function (e) {
            $('body').append($('<form/>', {
                id: 'form',
                method: 'POST',
                action: '<?php echo $this->basePath('/manager/contest-details'); ?>'
            }));

            $('#form').append($('<input/>', {
                type: 'hidden',
                name: 'id',
                value: $(this).attr('contest_id')
            }));

            $('#form').submit();

            return false;
        });

        $('.delete').click(function () {
            if (confirm("Do you want to delete")) {
                $.ajax({
                    url: '<?php echo $this->basePath('/manager/delete-contest'); ?>',
                    type: 'POST',
                    data: 'id=' + $(this).attr('contest_id'),
                    success: function (response) {
                        $('#create-contest-modal').modal('hide');
                        bootbox.alert(response.message, function () {
                            if (response.success) {
                                location.reload();
                            }
                        });
                    }
                });
            }
            return false;
        });

        $('.edit').click(function () {
            $.ajax({
                url: '<?php echo $this->basePath('/manager/get-contest-detail'); ?>',
                type: 'POST',
                data: 'id=' + $(this).attr('contest_id'),
                success: function (response) {
                    $('#id').val(response.data.id);
                    $('#name').val(response.data.name);
                    $('#description').data("wysihtml5").editor.setValue(response.data.description);
                    $('#thumbnail_name').show();
                    $('#thumbnail_name').val((response.data.thumbnail).substring(10));
                    $('#entryEndDate').val(response.data.entry_end_date);
                    $('#winnersAnnounceDate').val(response.data.winners_announce_date);
                    $('#votingStartDate').val(response.data.voting_start_date);
                    $('#entryLimit').val(response.data.max_no_of_photos);
                    if (response.data.is_exclusive == 1) {
                        $("input[name='exclusive'][value=0]").parent().removeClass('checked');
                        $("input[name='exclusive'][value=1]").parent().addClass('checked');
                    } else {
                        $("input[name='exclusive'][value=1]").parent().removeClass('checked');
                        $("input[name='exclusive'][value=0]").parent().addClass('checked');
                    }
                    $('#type').val(response.data.type_id);
                    $('#create-contest-modal').modal('show');
                }
            });
        });


        //pagination
        $('.page-number').click(function () {
            page = $(this).attr('value');
            window.location.href = "<?php echo $this->basePath('/manager?page='); ?>" + page;
        });

    });

    $("form#create-contest-form").submit(function () {

        entryEndDate = $('#entryEndDate').val();
        winnersAnnounceDate = $('#winnersAnnounceDate').val();
        votingStartDate = $('#votingStartDate').val();

        entryEndDateTime = convertDateToTime(entryEndDate);
        winnersAnnounceDateTime = convertDateToTime(winnersAnnounceDate);
        votingStartDateTime = convertDateToTime(votingStartDate);

        if (votingStartDateTime <= entryEndDateTime || winnersAnnounceDateTime <= votingStartDateTime) {
            bootbox.alert('Please check the dates');
        } else {
            var formData = new FormData($(this)[0]);

            $.ajax({
                url: '<?php echo $this->basePath('/manager/save-contest'); ?>',
                type: 'POST',
                data: formData,
                async: true,
                success: function (response) {
                    $('#create-contest-modal').modal('hide');
                    bootbox.alert(response.message, function () {
                        if (response.success) {
                            location.reload();
                        } else {
                            $('#create-contest-modal').modal('show');
                        }
                    });
                },
                cache: false,
                contentType: false,
                processData: false
            });
        }
        return false;
    });

    function convertDateToTime(myDate) {
        myDate = myDate.split("-");
        var newDate = myDate[1] + "/" + myDate[0] + "/" + myDate[2];
        return new Date(newDate).getTime();
    }

</script>
