<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/library/metronic/template/assets/plugins/bootstrap-datepicker/css/datepicker.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/library/metronic/template/assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/library/metronic/template/assets/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css'); ?>">
<style>
    table>tbody>tr>td, table>thead>tr>th {
        vertical-align: middle !important;
        text-align: center !important;
    }
    .help-block {
        margin-bottom: auto !important;
        font-size: inherit !important;
        font-weight: inherit !important;
    }
    a.btn-circle{
        width: 30px;
        height: 30px;
        text-align: center;
        padding: 6px 0;
        font-size: 12px;
        line-height: 18px;
        border-radius: 50% !important;
        -moz-border-radius: 50% !important;
        -webkit-border-radius: 50% !important;
    }
</style>
<!-- END PAGE LEVEL STYLES -->

<div class="jumbotron">
    <a class="pull-left" href="<?php echo $this->config('admin_main_site', 'url') ?>">
        <i class="fa fa-backward"></i> Go to main site
    </a>
    <?php if ($add_contest) { ?>
        <a class="btn btn-primary pull-right open-modal" data-toggle="modal" href="#create-contest-modal" onclick="resetForm();">
            Create Contest
        </a>
        <?php
    } else {
        //don't show add contest
    }
    ?>
    <div class="portlet">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-trophy"></i>Contests
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-advance table-hover">
                    <thead>
                        <tr>                            
                            <th>
                                <i class="fa fa-picture-o"></i> Thumbnail
                            </th>
                            <th>
                                <i class="fa"></i> Name
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-calendar"></i> Entry Start Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-calendar"></i> Entry End Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-calendar"></i> Voting Start Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-calendar"></i> Winners Announce Date
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-group"></i> Entries Limit
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-star"></i> Exclusive
                            </th>
                            <th>
                                <i class="fa"></i> Type
                            </th>
                            <th>
                                <i class="fa"></i> Publish
                            </th>
                            <th>
                                <i class="fa"></i> Actions
                            </th>                               
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($contests as $contest) { ?>
                            <tr>
                                <td>                                    
                                    <img src="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>" alt="Image not available" style="width:100px" />
                                </td>
                                <td class="highlight">
                                    <?php if ($review_contest) { ?>
                                        <a class="name" contest_id="<?php echo $contest['id']; ?>">
                                            <?php echo $contest['name']; ?>
                                        </a>
                                    <?php } else { ?>
                                        <?php echo $contest['name']; ?>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php echo date("F jS, Y", strtotime($contest['entry_start_date'])); ?>
                                </td>
                                <td>
                                    <?php echo date("F jS, Y", strtotime($contest['entry_end_date'])); ?>
                                </td>
                                <td>
                                    <?php echo date("F jS, Y", strtotime($contest['voting_start_date'])); ?>
                                </td>
                                <td>
                                    <?php echo date("F jS, Y", strtotime($contest['winners_announce_date'])); ?>
                                </td>
                                <td>
                                    <?php echo $contest['max_no_of_photos']; ?>
                                </td>
                                <td>
                                    <?php echo $contest['is_exclusive'] ? 'YES' : 'NO'; ?>
                                </td>
                                <td>
                                    <?php echo $contest['type']; ?>
                                </td>
                                <td>
                                    <?php if($contest['coming_soon'] == 1) {?>
                                        <input type="checkbox" class="publish" contest_id="<?php echo $contest['id']; ?>" <?php if($contest['publish_contest'] == 1){ ?> checked="checked" <?php } ?> > 
                                    <?php } else {?>
                                        Contest has already started.
                                    <?php }?>
                                </td>
                                <td style="width: 150px;">                                   
                                        <?php if ($add_contest) { ?>
                                    <a contest_id="<?php echo $contest['id']; ?>" class="btn btn-default btn-xs edit btn-circle" title="Edit Contest">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </a>
                                            <?php
                                        } else {
                                            //don't show edit contest
                                        }
                                        ?>
                                        <?php if ($delete_contest) { ?>
                                    <a contest_id="<?php echo $contest['id']; ?>" class="btn btn-default btn-xs delete btn-circle" title="Delete Contest">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                            <?php
                                        } else {
                                            //don't show delete contest
                                        }
                                        ?>
                                    <a href="<?php echo $this->config('main_site', 'url').'/contests/details/id/'.$contest['id']; ?>" class='btn btn-default btn-xs btn-circle' target="_blank" title="View Contest">
                                             <i class="fa fa-eye"></i>
                                        </a>
                                   </td>                                    
                            </tr>
                        <?php } ?>                        
                    </tbody>
                </table>
            </div>
            <div>
                <ul class="pagination pull-right">
                    <li>
                        <?php if ($totalPages > 1) { ?>
                            <a class="page-number" value="<?php echo $currentPage == 1 ? $totalPages : $currentPage - 1; ?>">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        </li>
                        <?php for ($i = 1; $i <= $totalPages; $i++) { ?>
                            <li>
                                <a class="page-number" value="<?php echo $i; ?>">
                                    <?php echo $i; ?>
                                </a>
                            </li>
                        <?php } ?>
                        <li>
                            <a class="page-number" value="<?php echo $currentPage == $totalPages ? 1 : $currentPage + 1; ?>">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        <?php } ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="modal fade" id="create-contest-modal" role="basic" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" style="width: 750px !important">
            <div class="modal-content">
                <div id="sumbit-loader" style=" display: none; position: absolute; z-index: 10; ">
                    <img src="<?php echo $this->basePath() ?>/img/loading.gif" style="width:100%; z-index: 10;"  />
                </div>
                <div class="modal-body">                    
                    <div class="row">
                        <div class="col-md-12 ">
                            <!-- BEGIN CREATE CONTEST FORM-->
                            <div class="portlet">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-reorder"></i> Create Contest

                                    </div>                
                                    <div class="tools">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="resetForm();"></button>
                                    </div>
                                </div>
                                <div class="portlet-body form">
                                    <form action="#" role="form" id="create-contest-form">
                                        <div class="form-body">
                                            <div class="alert alert-danger display-hide">
                                                <button class="close" data-close="alert"></button>
                                                You have some form errors. Please check below.
                                            </div>
                                            <div class="alert alert-success display-hide">
                                                <button class="close" data-close="alert"></button>
                                                Your form validation is successful!
                                            </div>
                                            <div class="form-group hidden">
                                                <input type="text" id="id" name="id" value='0'>
                                            </div>                        
                                            <div class="form-group col-md-12">
                                                <label class="control-label" for="name">
                                                    Contest Name
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <input type="text" data-required="1" class="form-control" id="name" name="name" placeholder="Enter Contest's Name">
                                            </div>                        
                                            <div class="form-group col-md-12">
                                                <label class="control-label" for="description">
                                                    Contest Description
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <textarea class="wysihtml5 form-control" id="description" name="description" rows="3" placeholder="Enter Contest's Description"></textarea>
                                            </div>
                                            <div class="form-group col-md-12">
                                                <label class="control-label" for="thumbnail">
                                                    Thumbnail
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <input type="file" id="thumbnail" name="thumbnail">
                                                <input type="text" class="form-control" disabled hidden id="thumbnail_name">
                                                <p class="help-block">Upload a square resolution image(For best appearance-Minimum Resolution: 300px X 300px)</p>
                                            </div>                                                   
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="type">
                                                    Contest Type
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <select class="form-control" id="type" name="type">
                                                    <?php foreach ($types as $type) { ?>
                                                        <option value="<?php echo $type['id']; ?>"><?php echo $type['type'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="entryLimit">
                                                    Entries Limit
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <input type="number" data-required="1" class="form-control" id="entryLimit" name="entryLimit" placeholder="Enter Contest's Entries Limit">
                                            </div>
                                            <div class="form-group col-md-12">
                                                <label class="help-block">Note: <i> Start dates are 12:00am and end dates are 11:59pm</i></label>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="entryStartDate">
                                                    Entry Start Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                    <input id="entryStartDate" name="entryStartDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="entryEndDate">
                                                    Entry End Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                    <input id="entryEndDate" name="entryEndDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-12" id="bracket_rounds_dates" style="display: none;border: 0.5px solid rgb(227, 227, 227); padding: 0px 20px; background-color: rgb(241, 241, 241);">
                                                <div class="form-group col-md-6">
                                                    <label class="control-label" for="br_round1">
                                                        Round One 64
                                                        <span class="required">
                                                            * <span style=" font-size: 10px; font-style: italic; color: grey">(voting start date)</span>
                                                        </span>
                                                    </label>
                                                    <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                        <input id="br_round1" name="br_round1" type="text" class="form-control" readonly>
                                                        <span class="input-group-btn">
                                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label" for="br_round2">
                                                        Round Two 32
                                                        <span class="required">
                                                            *
                                                        </span>
                                                    </label>
                                                    <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                        <input id="br_round2" name="br_round2" type="text" class="form-control" readonly>
                                                        <span class="input-group-btn">
                                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label" for="br_round3">
                                                        Sweet 16
                                                        <span class="required">
                                                            *
                                                        </span>
                                                    </label>
                                                    <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                        <input id="br_round3" name="br_round3" type="text" class="form-control" readonly>
                                                        <span class="input-group-btn">
                                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label" for="br_round4">
                                                        Elite 8
                                                        <span class="required">
                                                            *
                                                        </span>
                                                    </label>
                                                    <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                        <input id="br_round4" name="br_round4" type="text" class="form-control" readonly>
                                                        <span class="input-group-btn">
                                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label" for="br_round5">
                                                        Final 4
                                                        <span class="required">
                                                            *
                                                        </span>
                                                    </label>
                                                    <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                        <input id="br_round5" name="br_round5" type="text" class="form-control" readonly>
                                                        <span class="input-group-btn">
                                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label" for="br_round6">
                                                        Championship Round
                                                        <span class="required">
                                                            *
                                                        </span>
                                                    </label>
                                                    <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                        <input id="br_round6" name="br_round6" type="text" class="form-control" readonly>
                                                        <span class="input-group-btn">
                                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                        </span>
                                                    </div>
                                                </div>                                                
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="votingStartDate">
                                                    Voting Start Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                    <input id="votingStartDate" name="votingStartDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label class="control-label" for="winnersAnnounceDate">
                                                    Winners Announce Date
                                                    <span class="required">
                                                        *
                                                    </span>
                                                </label>
                                                <div class="input-group input-medium date date-picker" data-date-format="mm-dd-yyyy" data-date-start-date="+0d">
                                                    <input id="winnersAnnounceDate" name="winnersAnnounceDate" type="text" class="form-control" readonly>
                                                    <span class="input-group-btn">
                                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label>Is Exclusive Contest?</label>
                                                <div class="radio-list" id="exclusive">
                                                    <label class="radio-inline">
                                                        <div class="radio"><span><input type="radio" name="exclusive" id="exclusive-yes" value="1"></span></div> Yes </label>
                                                    <label class="radio-inline">
                                                        <div class="radio"><span><input type="radio" name="exclusive" id="exclusive-no" value="0" ></span></div> No </label>
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label>Would you like to publish the contest?</label>
                                                <div class="radio-list" id="publishContest">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="publishContest" value="1"> Yes </label>
                                                    <label class="radio-inline">
                                                        <input type="radio" name="publishContest" value="0"> No </label>
                                                </div>
                                            </div>                                            
                                            <div class="form-actions col-md-12">
                                                <button type="submit" class="btn blue" id="form-submit" >Submit</button>
                                                <button type="button" class="btn default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                            </div>
                                    </form>
                                </div>
                            </div>
                            <!-- END CREATE CONTEST FORM-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL SCRIPTS -->

<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('library/metronic/template/assets/scripts/custom/components-pickers.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('library/metronic/template/assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js'); ?>"></script>
<script src="<?php echo $this->basePath('library/metronic/template/assets/scripts/custom/components-editors.js'); ?>"></script>

<!-- END PAGE LEVEL PLUGINS -->
<script>

    $(document).ready(function () {
        App.init();
        ComponentsPickers.init();
        ComponentsEditors.init();
        //handleValidation();
        $('.open-modal').click(function () {
            $("input[name='exclusive'][value=1]").parent().removeClass('checked');
            $("input[name='exclusive'][value=0]").parent().removeClass('checked');
            $("input[name='publishContest'][value=1]").parent().removeClass('checked');
            $("input[name='publishContest'][value=0]").parent().removeClass('checked');
            $('form#create-contest-form').trigger('reset');
            $('#thumbnail_name').hide();
        });
        
        $('#type').on('change',function () {
            var type = $('select[name=type]').val()
            if(type == 3 ){
                $('#entryLimit').val("64");
                $('#entryLimit').attr('readonly',true);
                $('div#bracket_rounds_dates').css('display', 'block');
                $('#br_round1').val($('#votingStartDate').val());
            } else {
                resetForm();
            }
        });
        
        
        $('#votingStartDate').change(function(){
            var type = $('select[name=type]').val()
            if(type == 3 ){
                $('#br_round1').val($('#votingStartDate').val());
            }
        });
        
        $('#br_round1').change(function(){
            var type = $('select[name=type]').val()
            if(type == 3 ){
                $('#votingStartDate').val($('#br_round1').val());
            }
        });

        $('.name').click(function (e) {
            $('body').append($('<form/>', {
                id: 'form',
                method: 'POST',
                action: '<?php echo $this->basePath('/manager/contest-details'); ?>'
            }));

            $('#form').append($('<input/>', {
                type: 'hidden',
                name: 'id',
                value: $(this).attr('contest_id')
            }));

            $('#form').submit();

            return false;
        });

        $('.delete').click(function () {
            if (confirm("Do you want to delete")) {
                $.ajax({
                    url: '<?php echo $this->basePath('/manager/delete-contest'); ?>',
                    type: 'POST',
                    data: 'id=' + $(this).attr('contest_id'),
                    success: function (response) {
                        $('#create-contest-modal').modal('hide');
                        bootbox.alert(response.message, function () {
                            if (response.success) {
                                location.reload();
                            }
                        });
                    }
                });
            }
            return false;
        });
        
        $('.publish').click(function () {
        var msg;
        var publish_contest;
            if (this.checked) {
               msg = "Do you want to publish the contest?";
               publish_contest = 1;
            } else{
                msg = "Do you want to hide the contest?";
                publish_contest = 0;
            }
            if (confirm(msg)) {
                $.ajax({
                    url: '<?php echo $this->basePath('/manager/publish-contest'); ?>',
                    type: 'POST',
                    data: 'id=' + $(this).attr('contest_id') + '&publish_contest=' + publish_contest,
                    success: function (response) {
                        $('#create-contest-modal').modal('hide');
                        bootbox.alert(response.message, function () {                            
                            location.reload();                            
                        });
                    }
                });
            }
            return false;
        });

        $('.edit').click(function () {
            $.ajax({
                url: '<?php echo $this->basePath('/manager/get-contest-detail'); ?>',
                type: 'POST',
                data: 'id=' + $(this).attr('contest_id'),
                success: function (response) {
                    console.log(response);
                    $('#id').val(response.data.id);
                    $('#name').val(response.data.name);
                    $('#description').data("wysihtml5").editor.setValue(response.data.description);
                    $('#thumbnail_name').show();
                    $('#thumbnail_name').val((response.data.thumbnail).substring(10));
                    $('#entryStartDate').val(reformatDate(response.data.entry_start_date));
                    $('#entryEndDate').val(reformatDate(response.data.entry_end_date));
                    $('#winnersAnnounceDate').val(reformatDate(response.data.winners_announce_date));
                    $('#votingStartDate').val(reformatDate(response.data.voting_start_date));
                    $('#entryLimit').val(response.data.max_no_of_photos);
                    if (response.data.is_exclusive == 1) {
                        $("input[name='exclusive'][value=0]").parent().removeClass('checked');
                        $("input[name='exclusive'][value=1]").parent().addClass('checked');
                    } else {
                        $("input[name='exclusive'][value=1]").parent().removeClass('checked');
                        $("input[name='exclusive'][value=0]").parent().addClass('checked');
                    }
                    if (response.data.publish_contest == 1) {
                        $("input[name='publishContest'][value=0]").parent().removeClass('checked');
                        $("input[name='publishContest'][value=1]").parent().addClass('checked');
                    } else {
                        $("input[name='publishContest'][value=1]").parent().removeClass('checked');
                        $("input[name='publishContest'][value=0]").parent().addClass('checked');
                    }
                    $('#type').val(response.data.type_id);
                    $('#create-contest-modal').modal('show');
                    if(response.data.type_id == "3"){
                        $('#entryLimit').attr('readonly',true);
                        $('div#bracket_rounds_dates').css('display', 'block');
                        $('#br_round1').val(reformatDate(response.data.round1));
                        $('#br_round2').val(reformatDate(response.data.round2));
                        $('#br_round3').val(reformatDate(response.data.round3));
                        $('#br_round4').val(reformatDate(response.data.round4));
                        $('#br_round5').val(reformatDate(response.data.round5));
                        $('#br_round6').val(reformatDate(response.data.round6));                        
                    }
                }
            });
        });


        //pagination
        $('.page-number').click(function () {
            page = $(this).attr('value');
            window.location.href = "<?php echo $this->basePath('/manager?page='); ?>" + page;
        });

    });
    
    $("form#create-contest-form").submit(function () {
        contestType = $('select[name=type]').val();
        entryStartDate = $('#entryStartDate').val();
        entryEndDate = $('#entryEndDate').val();
        winnersAnnounceDate = $('#winnersAnnounceDate').val();
        votingStartDate = $('#votingStartDate').val();

        entryStartDateTime = convertDateToTime(entryStartDate);
        entryEndDateTime = convertDateToTime(entryEndDate);
        winnersAnnounceDateTime = convertDateToTime(winnersAnnounceDate);
        votingStartDateTime = convertDateToTime(votingStartDate);

        if (entryStartDateTime > entryEndDateTime || votingStartDateTime <= entryEndDateTime || winnersAnnounceDateTime <= votingStartDateTime) {
            $('#create-contest-modal').modal('hide');
            bootbox.alert('Please check the dates', function () {
                $('#create-contest-modal').modal('show');
            });
        } else if (contestType == '3' && !checkBracketRoundDates()) {              
            $('#create-contest-modal').modal('hide');
            bootbox.alert('Please check the dates', function () {
                $('#create-contest-modal').modal('show');
            });
        } else {
            $('#form-submit').attr('disabled',true);
            $('#sumbit-loader').css('display', 'block');
            var formData = new FormData($(this)[0]);

            $.ajax({
                url: '<?php echo $this->basePath('/manager/save-contest'); ?>',
                type: 'POST',
                data: formData,
                async: true,
                success: function (response) {
                    $('#create-contest-modal').modal('hide');
                    $('#sumbit-loader').css('display', 'none');
                    bootbox.alert(response.message, function () {
                        if (response.success) {
                            location.reload();
                        } else {
                            $('#create-contest-modal').modal('show');
                            $('#form-submit').attr('disabled',false);
                        }
                    });
                },
                cache: false,
                contentType: false,
                processData: false
            });               
        }
        return false;
    });
    
    function resetForm() {
        $('#entryLimit').val("");
        $('#entryLimit').attr('readonly',false);
        $('#sumbit-loader').css('display', 'none');
        $('div#bracket_rounds_dates').css('display', 'none');
        $('#form-submit').attr('disabled',false);        
    }
    
    function checkBracketRoundDates() {
        winnersAnnounceDate = $('#winnersAnnounceDate').val();
        votingStartDate = $('#votingStartDate').val();
        
        winnersAnnounceDateTime = convertDateToTime(winnersAnnounceDate);
        votingStartDateTime = convertDateToTime(votingStartDate);
        
        brRound1 = $('#br_round1').val();
        brRound2 = $('#br_round2').val();
        brRound3 = $('#br_round3').val();
        brRound4 = $('#br_round4').val();
        brRound5 = $('#br_round5').val();
        brRound6 = $('#br_round6').val();

        brRound1 = convertDateToTime(brRound1);
        brRound2 = convertDateToTime(brRound2);
        brRound3 = convertDateToTime(brRound3);
        brRound4 = convertDateToTime(brRound4);
        brRound5 = convertDateToTime(brRound5);
        brRound6 = convertDateToTime(brRound6);
        
        if((brRound1 < brRound2) && (brRound2 < brRound3) && (brRound3 < brRound4) && (brRound4 < brRound5) && (brRound5 < brRound6) && (brRound6 < winnersAnnounceDateTime) &&(votingStartDateTime == brRound1)) {
            return true;
        } else {
            return false;
        }
    }
    
    function convertDateToTime(myDate) {
        myDate = myDate.split("-");        
        var newDate = myDate[0] + "/" + myDate[1] + "/" + myDate[2];
        return new Date(newDate).getTime();
    }

    function reformatDate(dateStr)
    {
        dArr = dateStr.split("-");  // ex input "2010-01-18"
        return dArr[1] + "-" + dArr[2] + "-" + dArr[0]; //ex out: "01-18-2010"
    }

</script>
