<div class="jumbotron">
    <a class="pull-left" href="<?php echo $this->config('admin_main_site', 'url') ?>">
        <i class="fa fa-backward"></i> Go to main site
    </a>   
<div class="portlet">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-trophy"></i>Voting Details 
            </div>
        </div>
        <?php
            if($totalPages >= 1) {?>
                <div class="portlet-body">
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-advance table-hover">
                        <thead>
                            <tr>                                                      
                                <th>
                                    <i class="fa"></i> Name
                                </th>                           
                                <th class="hidden-xs">
                                     Round
                                </th>
                                <th class="hidden-xs">
                                     Rating
                                </th>
                                <th class="hidden-xs">
                                     IP Address
                                </th>
                                <th class="hidden-xs">
                                     Voted At
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($VotingDetails as $details) { ?>
                                <tr>
                                    <td>
                                        <?php

                                            if($details['f_name'].$details['l_name'] == "") {
                                                echo $details['member_id'];
                                            } else{
                                               echo $details['f_name']." " .$details['l_name'];
                                            }
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo $details['round']; ?>
                                    </td>
                                    <td>
                                        <?php echo $details['rating']; ?>
                                    </td>                          
                                    <td>
                                        <?php echo $details['ip_address']; ?>
                                    </td>
                                    <td>
                                        <?php echo $details['created_at']; ?>
                                    </td>
                                </tr>
                            <?php } ?>                        
                        </tbody>
                    </table>
                </div>
                <div>
                <ul class="pagination pull-right">
                    <li>
                        <?php if ($totalPages > 1) { ?>
                            <a class="page-number" value="<?php echo $currentPage == 1 ? $totalPages : $currentPage - 1; ?>">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        </li>
                        <?php for ($i = 1; $i <= $totalPages; $i++) { ?>
                            <li>
                                <a class="page-number" value="<?php echo $i; ?>">
                                    <?php echo $i; ?>
                                </a>
                            </li>
                        <?php } ?>
                        <li>
                            <a class="page-number" value="<?php echo $currentPage == $totalPages ? 1 : $currentPage + 1; ?>">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        <?php } ?>
                    </li>
                </ul>
            </div>
        </div>
        <?php }else{
                echo "<h3>No Votes For This Image Till Now..!!!</h3>";
        }?>
    </div>
</div>

<script>
        $('.page-number').click(function () {
            page = $(this).attr('value');
            window.location.href = "<?php echo $this->basePath('/manager/voting-details/'. "$cMediaId" .'?page='); ?>" + page;
        });    
</script>