<table>
    <tr>               
        <td style="width:52em;font-family: Trebuchet MS;font-size: 15px;">    
            <table style="font-family: Trebuchet MS;width:100%;">
                <tr>
                    <td style="padding: 2px;text-align: center;font-size: 50px;">
                        <a href="<?php echo $main_site_url; ?>" style="text-decoration: none;color:inherit;">
                            <img src="<?php echo $main_site_url; ?>/contests/img/mail_head.png"/>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <hr style="border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px;">
                        Hi <?php echo $f_name . ' ' . $l_name; ?>,
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px 20px 15px;">
                        BIG NEWS - you have made it into Championship! Your image "<?php echo $title; ?>" has come a long way! This means you have also won a free gallery mounted high definition photoghraphic print up to 16x20!
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px 20px 15px;">
                        When the contest is over and the winner is announced, you will receive a new email containing two coupons codes. One coupon code will be used to redeem your Core Four prize (a free print of your image, up to a 12" x 18"). The other coupon code will be used to redeem your free gallery mounted HD photographic print up to 16" X 20". You will have 30 days after the contest's end date to redeem your prize.
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px 20px 15px;">
                        Since you have advanced to the Championship, let's review what is at stake - Winner of the Championship will receive $250 credit towards a YourArtGallery.com purchase & a free Platinum Membership for 6 months.
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px;">
                        Congratulations again, and we wish you the best of luck!<br>
                        The Your Art Gallery Team
                    </td>
                </tr>
            </table>
            <table style="text-align: center;padding-top:50px;font-size: 13px;width: 100%;">
                <tr><td style="padding: 5px;">The community continues at...</td></tr>
                <tr>
                    <td>
                        <a href="https://www.facebook.com/YourArtGallery" ><img src="<?php echo $main_site_url . '/assets/files/content_files/facebook_share_new.png'; ?>" alt="" /></a>
                        <a href="https://instagram.com/Your.Art.Gallery/" ><img src="<?php echo $main_site_url . '/assets/files/content_files/instagram_share_new.png'; ?>" alt="" /></a>
                        <a href="https://twitter.com/YourArtGallery" ><img src="<?php echo $main_site_url . '/assets/files/content_files/twitter_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.linkedin.com/company/your-art-gallery-llc" ><img src="<?php echo $main_site_url . '/assets/files/content_files/linkedin_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.pinterest.com/yourartgallery" ><img src="<?php echo $main_site_url . '/assets/files/content_files/pinterest_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $main_site_url . '/assets/files/content_files/youtube_share_new.png'; ?>" alt="" /></a>
                        <a href="http://yaguniversity.tumblr.com" ><img src="<?php echo $main_site_url . '/assets/files/content_files/yag_university_share_new.png'; ?>" alt="" /></a>
                    </td>
                </tr>                
            </table>
            <table style="width: 100%;padding: 0px 60px;">
                <tr>
                    <td>
                        <hr style="margin-top: 40px;margin-bottom: 30px;border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>           
            <table style="text-align: center;font-size: 13px;width: 100%;">
                <tr>
                    <td> <a href="<?php echo $main_site_url; ?>" style="margin:5px;"><img src="<?php echo $main_site_url . '/assets/themes/yag/images/main_logo.png'; ?>" alt="" width="100px" height="68px"/></a></td>                      
                </tr>
                <tr style="font-size: 10px;"><td><a href="<?php echo $main_site_url; ?>" style="color: #653F8A;font-weight: bold;font-size: 10px;">YourArtGallery.com</a></td></tr>
                <tr><td>43 W 24th St. 2nd FL</td></tr>
                <tr><td>New York, NY 10010</td></tr>
                <tr><td>646.638.7171</td></tr>
                <tr><td><a href="mailto:info@yourartgallery.com" style="text-decoration: none;color:inherit;">info@yourartgallery.com</a></td></tr>        
            </table>
            <table style="width: 100%;padding: 0px 60px;">
                <tr>
                    <td>
                        <hr style="margin-top: 30px;margin-bottom: 30px;border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>       
        </td>
    </tr>
</table>