<div>
    Hi <?php echo $user_data['f_name'].' '.$user_data['l_name'];?>,<br><br>

    <p>Your image _{IMAGE NAME}_ entered in the _{NAME OF CONTEST}_ has been disqualified and removed from the contest because it violated our contest's rules and regulations. For more information or any questions, you may contact us at info@yourartgallery.com.
        The results are in! Voting for the "<?php echo $name; ?>" contest that you entered has concluded. Come find out the winners by clicking <a href="<?php echo $main_site_url.'/contests/photo-contest/rankings/'.$id; ?>">here</a>.</p><br>


    Sincerely,<br>
    The Your Art Gallery Team
</div>