<table>
    <tr>

        <td style="width:52em;font-family: Trebuchet MS;font-size: 15px;">    
            <table style="width:100%;">
                <tr>
                    <td style="padding: 2px;text-align: center;">
                        <a href="<?php echo $contest['main_site_url']; ?>" style="text-decoration: none;color:inherit;">
                            <img src="<?php echo $contest['main_site_url']; ?>/contests/img/mail_head.png"/>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <hr style="border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>
            <table style="width:38%;float: left;">
                <tr>
                    <td>
                        <img src="<?php echo $awsPath . $contest['thumbnail']; ?>" width="287px" height="288px;">
                    </td>
                </tr>
            </table>
            <table style="font-size: 15px;font-family: Trebuchet MS;width:62%;float: left;padding-left: 8px;line-height: 21px;">
                <tr>
                    <td style="line-height: 26px;">                      
                        Hi <?php echo $winner['f_name']; ?>,<br>
                        Congratulations! You are the FIRST PLACE winner of
                        our "<?php echo $contest['name']; ?>"! Your photo "<?php echo $winner['title']; ?>"
                        had the highest rating of all <?php echo $totalEntries; ?> entries! Great job!
                    </td>
                </tr>                                
                <tr><td style="padding-top: 20px;">As a reminder, you have won:</td><tr>
                <tr><td>- $250 YourArtGallery.com credit</td></tr>
                <tr><td style="padding-top: 2px;">- Gallery Plexi HD Photographic Print </td></tr> 
                <tr><td style="padding-left: 35px;">(up to 16" x 20")</td></tr>
                <tr><td style="padding-top: 2px;">- Free 6 months Platinum Membership</td></tr> 
                <tr><td style="padding-left: 35px;">(automatically upgraded)</td></tr>
                <tr><td style="padding-top: 2px;">- A highlight in our YAG University Newsletter</td></tr>
            </table>
            <table style="width:38%;clear: both;float: left;padding-top: 20px;">
                <tr>
                    <td>
                        <img src="<?php echo $mediaImage($winner, 'samples', '287'); ?>" alt="<?php echo $winner['title'] ?>" width="287px" height="218px;">
                    </td>              
                </tr>
            </table>
            <table style="font-size: 15px;font-family: Trebuchet MS;width:62%;float: left;padding-left: 8px;line-height: 26px;padding-top: 20px;">        
                <tr>
                    <td style="padding-top: 15px;">
                        Your coupon code for $250 YourArtGallery Credit is:
                        <b><?php echo $promoCode2; ?></b>. Enter this promo code at check out.                                
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 15px;">
                        Your coupon code for the Gallery Plexi HD Photographic print is:
                        <b><?php echo $promoCode; ?></b>. Enter this promo code at check out.                                
                    </td>
                </tr>
                <tr>      
                    <td style="padding-top: 15px;">
                        * All prizes must be redeemed within 30 days of the contest's end date.
                    </td>
                </tr>
                <tr> <td style="padding-top: 15px;">
                        Congratulations again and thanks for participating!
                    </td>
                <tr>
                <tr><td style="padding-top: 18px;text-align: center;font-size: 21px;">The Your Art Gallery Team</td></tr>
            </table>
            <table style="border-spacing: 0; border-width: 0; font-size: 15px;padding-top: 50px;font-family: Trebuchet MS;width: 100%;">
                <tr style="background-color: #EDEFEA;">
                    <?php foreach ($contestTopWinners as $row) { ?>
                        <td style="width: 20%;padding: 10px 5px;">
                            <table>
                                <tr>
                                    <td style="color: #5A5A5A;font-weight: bold;font-size: 14px;">
                                        <?php echo $ordinal($row['rank']); ?>&nbsp;Place
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="<?php echo $contest['main_site_url'] . '/photo/' . $kCrypt->enc($row['media_id']) . '/' . str_replace(" ", "-", $row['title']) . '.html' ?>" style="text-decoration: none;">
                                            <img src="<?php echo $mediaImage($row, 'icons', '145', '145'); ?>" width="145px" height="145px">
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="text-align: center;">
                                        <a href="<?php echo $contest['main_site_url'] . '/' . $row['username']; ?>" style="text-decoration: none;color:inherit;font-size: 14px;">
                                            <?php
                                            $displayName = $row['f_name'] . ' ' . $row['l_name'];
                                            if (strlen($displayName) > 14) {
                                                echo substr($displayName, 0, 13) . '..';
                                            } else {
                                                echo $displayName;
                                            }
                                            ?>
                                        </a>
                                    </td>
                                </tr>
                            </table>       
                        </td>   
                    <?php } ?>    
                </tr>    
            </table>
            <table style="text-align: center;padding-top:50px;font-size: 13px;width: 100%;">
                <tr><td style="padding: 5px;">The community continues at...</td></tr>
                <tr>
                    <td>
                        <a href="https://www.facebook.com/YourArtGallery" ><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/facebook_share_new.png'; ?>" alt="" /></a>
                        <a href="https://instagram.com/Your.Art.Gallery/" ><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/instagram_share_new.png'; ?>" alt="" /></a>
                        <a href="https://twitter.com/YourArtGallery" ><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/twitter_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.linkedin.com/company/your-art-gallery-llc" ><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/linkedin_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.pinterest.com/yourartgallery" ><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/pinterest_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/youtube_share_new.png'; ?>" alt="" /></a>
                        <a href="http://yaguniversity.tumblr.com" ><img src="<?php echo $contest['main_site_url'] . '/assets/files/content_files/yag_university_share_new.png'; ?>" alt="" /></a>
                    </td>
                </tr>                
            </table>
            <table style="width: 100%;padding: 0px 60px;">
                <tr>
                    <td>
                        <hr style="margin-top: 40px;margin-bottom: 30px;border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>           
            <table style="text-align: center;font-size: 13px;width: 100%;">
                <tr>
                    <td> <a href="<?php echo $contest['main_site_url']; ?>" style="margin:5px;"><img src="<?php echo $contest['main_site_url'] . '/assets/themes/yag/images/logo.png'; ?>" alt=""/></a></td>                      
                </tr>
                <tr style="font-size: 10px;"><td><a href="<?php echo $contest['main_site_url']; ?>" style="color: #653F8A;font-weight: bold;font-size: 10px;">YourArtGallery.com</a></td></tr>
                <tr><td>43 W 24th St. 2nd FL</td></tr>
                <tr><td>New York, NY 10010</td></tr>
                <tr><td>646.638.7171</td></tr>
                <tr><td><a href="mailto:info@yourartgallery.com" style="text-decoration: none;color:inherit;">info@yourartgallery.com</a></td></tr>        
            </table>
            <table style="width: 100%;padding: 0px 60px;">
                <tr>
                    <td>
                        <hr style="margin-top: 30px;margin-bottom: 30px;border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>       
        </td>
    </tr>
</table>
