<h1><?php echo 'An error occurred'; ?></h1>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
<h2><?php echo $this->message ?></h2>
<hr/>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
    <dt><?php echo 'File' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt><?php echo 'Message' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
    </dd>
    <dt><?php echo 'Stack trace' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php else: ?>
<dl>
    <dt><?php echo 'Type of error' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception['type'] ?></pre>
    </dd>
    <dt><?php echo 'File' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception['file'] ?>:<?php echo $this->exception['line'] ?></pre>
    </dd>
    <dt><?php echo 'Message' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception['message'] ?></pre>
    </dd>
    <dt><?php echo 'Stack trace' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"></pre>
    </dd>
</dl>
<?php endif ?>

