<div>
    Hi <?php echo $user_data['f_name'].' '.$user_data['l_name'];?>,<br><br>

    <p>Your image "<?php echo $user_data['title']; ?>" entered in the <b>"<?php echo $name; ?>"</b> has been disqualified and removed from the contest because it violated our contest's rules and regulations. For more information or any questions, you may contact us at info@yourartgallery.com.</p><br>


    Sincerely,<br>
    The Your Art Gallery Team
</div>