<div>
    Hi <?php echo $user_data['f_name'].' '.$user_data['l_name'];?>,<br><br>

    <p>It’s voting time! The <b>"<?php echo $name; ?>"</b> has officially begun. Be sure to share your entry with family, friends and on social media to increase your votes.  In the meantime, check out your competition <a href="<?php echo $main_site_url ?>/contests">here</a>. Good luck!</p><br>


    Sincerely, <br>
    The Your Art Gallery Team
</div>