<table>
    <tr>               
        <td style="width:52em;font-family: Verdana, Geneva, sans-serif;font-size: 15px;background-color: #fff;">    
            <table style="font-family: Verdana, Geneva, sans-serif;width:100%;">

                <tr>
                    <td style="padding: 2px;text-align: center;font-size: 50px;">
                        <a href="<?php echo $main_site_url; ?>" style="text-decoration: none;color:inherit;">
                            <img src="<?php echo $main_site_url; ?>/contests/img/mail_head.png"/>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <hr style="border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px 20px 15px;">
                        Hi Admin,
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px 20px 15px;">
                        The results for <b>"<?php echo $name; ?>"</b> has concluded. Winners are announced. Click <a href="<?php echo $main_site_url . '/contests/' . $contest_type . '/rankings/' . $id; ?>">here</a> to view winners.
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px 15px 20px 15px;">
                        Sincerely,<br>
                        The Your Art Gallery Team
                    </td>
                </tr>
            </table>
            <table style="text-align: center;padding-top:50px;font-size: 13px;width: 100%;">
                <tr><td style="padding: 5px;">The community continues at...</td></tr>
                <tr>
                    <td>
                        <a href="https://www.facebook.com/YourArtGallery" ><img src="<?php echo $main_site_url . '/assets/files/content_files/facebook_share_new.png'; ?>" alt="" /></a>
                        <a href="https://instagram.com/Your.Art.Gallery/" ><img src="<?php echo $main_site_url . '/assets/files/content_files/instagram_share_new.png'; ?>" alt="" /></a>
                        <a href="https://twitter.com/YourArtGallery" ><img src="<?php echo $main_site_url . '/assets/files/content_files/twitter_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.linkedin.com/company/your-art-gallery-llc" ><img src="<?php echo $main_site_url . '/assets/files/content_files/linkedin_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.pinterest.com/yourartgallery" ><img src="<?php echo $main_site_url . '/assets/files/content_files/pinterest_share_new.png'; ?>" alt="" /></a>
                        <a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $main_site_url . '/assets/files/content_files/youtube_share_new.png'; ?>" alt="" /></a>
                        <a href="http://www.yaguniversity.com" ><img src="<?php echo $main_site_url . '/assets/files/content_files/yag_university_share_new.png'; ?>" alt="" /></a>
                    </td>
                </tr>                
            </table>
            <table style="width: 100%;padding: 0px 60px;">
                <tr>
                    <td>
                        <hr style="margin-top: 40px;margin-bottom: 30px;border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>           
            <table style="text-align: center;font-size: 13px;width: 100%;">
                <tr>
                    <td> <a href="<?php echo $main_site_url; ?>" style="margin:5px;"><img src="<?php echo $main_site_url . '/assets/themes/yag/images/logo.png'; ?>" alt=""/></a></td>                      
                </tr>
                <tr style="font-size: 10px;"><td><a href="<?php echo $main_site_url; ?>" style="color: #653F8A;font-weight: bold;font-size: 10px;">YourArtGallery.com</a></td></tr>
                <tr><td>43 W 24th St. 2nd FL</td></tr>
                <tr><td>New York, NY 10010</td></tr>
                <tr><td>646.638.7171</td></tr>
                <tr><td><a href="mailto:info@yourartgallery.com" style="text-decoration: none;color:inherit;">info@yourartgallery.com</a></td></tr>        
            </table>
            <table style="width: 100%;padding: 0px 60px;">
                <tr>
                    <td>
                        <hr style="margin-top: 30px;margin-bottom: 30px;border-top: 2px solid #E1E5E6 !important;">
                    </td>
                </tr>
            </table>       
        </td>
    </tr>
</table>