<div>
    Hi <?php echo $user_data['f_name'].' '.$user_data['l_name'];?>,<br><br>

    <p>The results are in! Voting for the "<?php echo $name; ?>" that you entered has concluded. Come find out the winners by clicking <a href="<?php echo $user_data['type_id'] == 3 ? $main_site_url.'/contests/brackets/rankings/'.$id : $main_site_url.'/contests/photo-contest/rankings/'.$id; ?>">here</a>.</p><br>


    Sincerely,<br>
    The Your Art Gallery Team
</div>