<style>
    .rules {
        text-align: left;        
    }
    .rules-heading {
        border:1px solid grey; 
        width: 70%; 
        padding: 1%
    }
    ul li {
        list-style: disc;
    }
    a {
        color: #428bca;
    }
</style>
<div class="rules">
    <div class="inner_main clearfix">
        <div class="inner_txt clearfix">
            <h1 class="page-titleHead">Artist Challenge & Contests</h1>
        </div>
    </div>

    <div class="learn-more-contest-title">Photo Contest Rules & Regulations!</div>
    <h1 class="learn-more-sub-head">How to Enter:</h1>
    <ul>
        <li>All submissions are online via each  contest listing.</li>
        <li>Upload a new image or select an image from your existing portfolio. <i>Please note:</i> You will not be able to upload a new image if you have already used all available space in your portfolio, based on your subscription level.  In this case, consider upgrading your membership or replacing an image from your portfolio.</li>
        <li>Once your submission has been completed, you will be directed to a confirmation page.</li>
        <li>Only one submission per artist.</li>
    </ul> 

    <h1 class="learn-more-sub-head">Who May Enter:</h1>
    <p>Any professional, amateur, enthusiast or student photographic artist subscribed and a member of YOUR ART GALLERY.</p>

    <h1 class="learn-more-sub-head">Entry Fee:</h1>
    <p>There is not cost to enter!</p>

    <h1 class="learn-more-sub-head">Judging:</h1>
    <p>Entries will be judged based on the Your Art Gallery rating system, in which the rating and voting authority your peers and thousands of YAG visitors identify the winning images.</p>

    <h1 class="learn-more-sub-head">Consent Agreement:</h1>
    <p>Submission of an entry to each contest automatically constitutes the contestant’s acceptance of all contest rules and conditions, and affirms the contestant acceptance of being in accordance with the Your Art Gallery LLC, Terms of Service.  All applicants and contestants retain full copyright of any image submitted.  The use of submitted images comply with the <a href="<?php echo $this->config('main_site', 'url') ?>/terms-of-service"><i>Terms of Service agreement</i></a> of Your Art Gallery LLC., and <a href="<?php echo $this->config('main_site', 'url') ?>/artist.welcome.php"><i>Your Promotion Center</i></a> social media opt-in settings at, <a href="<?php echo $this->config('main_site', 'url') ?>/portfolio.php"><i>Edit Your Portfolio</i></a>.
        <br>
        <br>
        <i>Entries not complying with contest rules set forth will be disqualified.</i>
        <br>
        <br>                
        If you have questions about the above information or would like to know if your image is eligible, please contact us at <span class="blue-text">info@yourartgallery.com</span>.
    </p>
    <p>
        <span style="color: #68398C;font-weight:bold;">PLEASE NOTE:</span> You will retain full copyright of any image submitted. However, upon entering, you acknowledge and
        accept Duggal’s right to use your image for external purposes with adequate crediting to your full name as submitted by
        you to Duggal. This includes but is not limited to digital and print content, contest promotions, seasonal promotions and
        resizing for these purposes. Duggal will not exploit your image for any form of direct compensation.
    </p>
</div>