<?php
    $this->headMeta()->setProperty('twitter:card', 'summary');
    $this->headMeta()->setProperty('twitter:site', '@YourArtGallery');
    $this->headMeta()->setProperty('twitter:title', $contest['name']);
    
    
    if($shareMedia) {
        $this->headMeta()->setProperty('twitter:image', $this->mediaImage($shareMedia, 'samples'));
        $this->headMeta()->setProperty('twitter:description', 'The results are in! Check out the winners of the ' . $contest['name']);    
    } else {
        $this->headMeta()->setProperty('twitter:image', $this->config('aws', 'path') . $contest['thumbnail']);    
        $this->headMeta()->setProperty('twitter:description', 'The results are in! Check out the winners of the '.$contest['name'].' '.$this->config('main_site' ,'url') . '/contests/past-winners');
    }
    
    $this->headMeta()->setProperty('og:title', $contest['name']);
    $this->headMeta()->setProperty('og:type', 'website');
    if($shareMedia) {
        $this->headMeta()->setProperty('og:image', $this->mediaImage($shareMedia, 'samples'));
        $this->headMeta()->setProperty('og:description', 'The results are in! Check out the winners of the ' . $contest['name']);
    } else {
        $this->headMeta()->setProperty('og:image', $this->config('aws', 'path') . $contest['thumbnail']);
        $this->headMeta()->setProperty('og:description', 'The results are in! Check out the winners of the '.$contest['name'].' '.$this->config('main_site' ,'url') . '/contests/past-winners');
    }
?>
<style>
    /*    .media-art {
            padding: 5px;
        }
    */
    .col-md-2 {
        margin: 12px;
    }

    .media-art {
        width: 150px;
        height: 150px;
    }
    .media-art img {
        //width: 160px;
        width: 100%;
        height: 100%;
        border: 3px solid rgb(214, 216, 216);
        display: table-cell;
        vertical-align: middle;
        background-color: rgb(214, 216, 216);
    }
    .media-list-title {
       background-color: #8C8C8C;
        padding: 10px;
        margin: 15px 0px;
        width: 450px;
        font-size: 22px;
        color: white;
    }
    .contest {
        font-family: 'franklin_gothic_bookregular';
        font-weight: bold;
        color: #663f8e; 
    }
    .artist-name , .user-name, .rank {
        text-align: center;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis
    }
    .ranking-page {
        height: 70px;
    }
</style>
<div  class="home_content clearfix">
    <div class="inner_main clearfix">
        <div class="inner_txt clearfix">
            <h1 class="page-titleHead">ARTIST CHALLENGES AND CONTESTS</h1>
        </div>
    </div>

    <div class="contest clearfix" style="border:none">
        <div style=" margin: 2px;margin-bottom: 5px; ">
            What is art? It is your turn to help decide. These talented artist have been selected to show
            their work and we need you to choose your favorite image to win! Vote on your favorites to win! <br>
            Click the button below for a list of our other contests. <br>
            <button onclick="window.location = '<?php echo $this->basePath() ?>/active-contest'">Artist Challenge & Contests</button>
        </div>
        <?php
        $dStart = new DateTime(date("Y-m-d"));
        $dEnd = new DateTime($contest['winners_announce_date']);
        $dDiff = $dStart->diff($dEnd);
        ?>
        <?php if ($dEnd > $dStart): ?>
            <div class="clearfix"> 
                <div class="row">
                    <div class="right col-md-4 col-xs-4">
                        <button style="width: 100%;font-size: 28px;" onclick="window.location = '<?php echo $this->basePath() ?>/photo-contest/voting/<?php echo $contestId; ?>'">Get to Voting!</button>
                    </div>
                </div>
                <div class="row">
                    <div class="right" style="font-weight: bold;color: #000; padding-right: 12px">
                        Contest countdown: <?php echo $dDiff->days; ?> days remaining
                    </div>
                </div>
            </div>
            <br>
        <?php endif; ?>
        <div>
            <?php if ($dEnd > $dStart): ?>
                <div class="media-list-title">Current Standings</div>
            <?php else: ?>
                <div class="media-list-title">Final Standings</div>
            <?php endif; ?>
            <div class="media-list contest-list clearfix">
                <div class="row">
                    <?php foreach ($medias as $key => $media): ?>
                        <?php $i = $key + 1; ?>
                        <div class="col-md-2 col-xs-2">
                            <div class="media-art">
                                <a class="media_image" href="<?php echo $this->config('main_site', 'url').'/photo/'.$this->KCrypt()->enc($media['media_id']).'/'. str_replace(" ", "-", $media['title']).'.html' ?>" data-media_id="<?php echo $media['media_id'] ?>">
                                    <img mediaid="<?php echo $this->KCrypt()->enc($media['media_id']) ?>" class="mediaThumb" src="<?php echo $this->mediaImage($media, 'icons' , '150'); ?>" title="<?php echo $media['title'] ?>" alt="<?php echo $media['title'] ?>" />
                                </a> 
                                <div class="artist-name" style="font-size: 13px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $media['username'] ?>" class="onhover-ul font12 text-bold"><?php echo $media['f_name'].' '.$media['l_name']; ?></a></div>                                
                                <div class="rank"><strong style="font-size: 25px;color: #646567;"><?php echo $this->ordinal((($page - 1) * $size) + $i); ?></strong></div>
                            </div>
                        </div>
                        <?php if ($i != 1 && $i % 5 == 0): ?>
                        </div>
                        <div class="clearfix ranking-page"></div>
                        <div class="row">
                        <?php endif; ?>

                    <?php endforeach; ?>
                </div>
                <div class="clearfix ranking-page"></div>
            </div>

        </div>
    </div>

    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator-slide', array(
        'route' => 'photo-contest',
        'routeParams' => array(
            'action' => 'rankings',
            'id' => $this->contestId,
            'size' => $this->size
        )
    ));
    ?>
</div>
