<style>
  .contest {
    padding:0px;
  }
  .contest-title-blue {
    font-size: 28px;
    font-weight: bold;
    margin: 0% 0% 5% 0%;
    text-align: left;
    color: #68398c;
  }
  .contest-image{
    border: 4px solid #C8B64C;
    width: 150px;
  }
  .row-no-padding-margin{
    padding: 0px;
    margin:0px;
  }
  .no-padding-right{
    padding-right:0px;
  }

  #my-media-list {
    border: 2px solid #ccc;
    margin:0px;
  }
  .media-list-title {
    background-color: #C8B64C;
    padding: 2px;
    margin:15px 40px;
    width:200px;
    font-size: 22px;
  }
  .social_link, .pagination {
    padding: 5px;
  }
</style>
<div  class="home_content clearfix">
  <div class="inner_main clearfix">
    <div class="inner_txt clearfix">
      <h1 class="page-titleHead">Artist Challenge & Contests</h1>
    </div>
  </div>

  <div class="contest-list clearfix">
    <div class="contest row" style="border:none">
      <div class="col-md-6">
        <div class="contest-title-blue"><?php echo $contest['name']; ?></div>
        <div>Choose from one of your uploaded images and submit it for this
          contest or upload a new image!</div>
          <br>
        <div class="row row-no-padding-margin">
          <div class="col-md-5 contest-image">
            <img  src="<?php echo $this->basePath() ?>/img/contest/thumbnail/<?php echo $contest['thumbnail']; ?>"  alt="Contest Photo" />
          </div>
          <div class="col-md-7 ">
            <div>
              <button id="submitImage" value="Submit this Image">Submit this Image</button><br>
              *Full image will be shown for voting.
            </div>
            <div>or</div>
            <div>
              <button id="submitNewImage" value="Upload New Image">Upload New Image</button><br>
              *YAG Artist must have room in their portfolio if this option is selected.
            </div>
          </div>  
        </div>
        
        <br>
          <br>
        <div class="contest-description">
          <?php echo $contest['description']; ?>
          <br>
          <br>
          <div class="contest-dates">
            Open Entries End: <?php echo $contest['entry_end_date']; ?><br>
            Voting Begins: <?php echo $contest['entry_end_date']; ?>
          </div>                
        </div>
      </div> 
      <div class="col-md-6 no-padding-right">
        <div id="my-media-list" class="clearfix">
          <div class="media-list-title">Your Uploaded Art</div>
          <div class="media-list clearfix"></div>
        </div>
        <div class="social_link">
          <a href="https://www.facebook.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/facebook_share.png"  alt="Share to Facebook" /></a>
          <a href="https://twitter.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/twitter_share.png"  alt="Share to Twitter" /></a>
          <a href="https://instagram.com/Your.Art.Gallery/"><img src="<?php echo $this->basePath() ?>/img/instagram_share.png"  alt="Instagram" /></a>
          <a href="https://www.pinterest.com/yourartgallery/"><img src="<?php echo $this->basePath() ?>/img/pinterest_share.png"  alt="Share to Pinterest" /></a>
          <a href="https://plus.google.com"><img src="<?php echo $this->basePath() ?>/img/google_share.png"  alt="Share to Google" /></a>
          <a href="https://www.linkedin.com/company/your-art-gallery-llc"><img src="<?php echo $this->basePath() ?>/img/linkedin_share.png"  alt="Stumble It" /></a>
          <a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/youtube_share.png"  alt="Share to Youtube" /></a>            
        </div>
      </div> 
    </div>
  </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/js/helpers.js"></script>
<script type="text/javascript">
  loadHtml('<?php echo $this->basePath() ?>/media/get-my-media', '.media-list', '', function(){
    registerHoverFunction();
    registerFollowCursor();
  });
  
  $('#submitImage').click(function(){
    if($("input:radio[name=my_media]").is(":checked")){
      submitArt('<?php echo $contest['id']; ?>', $("input:radio[name=my_media]").val());
    } else {
      alert('Please select your art');
    }
  });
  
  function submitArt(contestId, mediaId) {
    var request = $.ajax({
      url:  '<?php echo $this->basePath() ?>/photo-contest/art-submission',
      type: "POST",
      data: {'media_id':mediaId, 'contestId': contestId},
      dataType: 'json',
    });

    request.done(function( msg ) {
      if(msg.success) {
        alert(1)
      } else {
        alert(msg.message)
      }
    });

    request.fail(function( jqXHR, textStatus ) {
      alert( "Request failed: " + textStatus );
    });
  }
</script>