<footer>                
    <div class="footer-top-container">
        <div class="wrapper">
            <div class="addthis_toolbox">   
<!--                <div class="social_link">

                    <a href="https://www.facebook.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/facebook_share.png"  alt="Share to Facebook" /></a>
                    <a href="https://twitter.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/twitter_share.png"  alt="Share to Twitter" /></a>
                    <a href="https://instagram.com/Your.Art.Gallery/"><img src="<?php echo $this->basePath() ?>/img/instagram_share.png"  alt="Instagram" /></a>
                    <a href="https://www.pinterest.com/yourartgallery/"><img src="<?php echo $this->basePath() ?>/img/pinterest_share.png"  alt="Share to Pinterest" /></a>
                    <a href="https://plus.google.com/+Yourartgallery/posts"><img src="<?php echo $this->basePath() ?>/img/google_share.png"  alt="Share to Google" /></a>
                    <a href="https://www.linkedin.com/company/your-art-gallery-llc"><img src="<?php echo $this->basePath() ?>/img/linkedin_share.png"  alt="Stumble It" /></a>
                    <a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/youtube_share.png"  alt="Share to Youtube" /></a>            
                    <a href="http://yaguniversity.tumblr.com"><img src="<?php echo $this->basePath() ?>/img/yag_university.png"  alt="YAG University" /></a>
                </div>-->
            </div>
        </div>
        <div class="footer-container">
            <footer class="wrapper clearfix">

                <div class="footer_box">
                    <h1>COMPANY INFO</h1>
                    <ul>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-us">About Us</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-our-prints">About Our Prints</a></li>
                        <li><a href="http://yaguniversity.tumblr.com/tagged/media" target="_blank">Media</a></li>
                        <li><a href="http://yaguniversity.tumblr.com/tagged/news" target="_blank">News & Press</a></li>
                        <li><a href="http://yaguniversity.tumblr.com/tagged/events" target="_blank">Events & Exhibitions</a></li>
                    </ul>
                </div>

                <div class="footer_box">
                    <h1>ORDER INFO</h1>          <ul>
                        <li><a id="loginPopup11" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=buyer">Track An Order</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/shipping-and-returns">Shipping Options</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/shipping-and-returns">Return Information</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/corporate-sales">Corporate Sales</a></li>
                    </ul>
                </div>

                <div class="footer_box" style="margin-right: 5px;">
                    <h1>HELP / FEEDBACK</h1>
                    <ul>
                        <li><a href="http://yaguniversity.tumblr.com/faq" target="_blank">FAQs</a></li>
                        <li><a href="http://yaguniversity.tumblr.com" target="_blank">Blog</a></li>
                        <li>
                            <a href="<?php echo $this->config('main_site', 'url') ?>/feedback">Feedback</a>
                        </li>
                    </ul>
                </div>

                <div class="footer_box" style="width: 14%;">
                    <h1>TERMS & POLICIES</h1>
                    <ul>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Sustainability Policy</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Privacy Policy</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Purchasing Policy</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/terms-of-service">Terms & Conditions</a></li>
                    </ul>
                </div>

                <div class="footer_box" style="width: 11%;">
                    <h1>CONTACT US</h1>
                    <ul>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/contact-us">Location / Hours</a></li>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/jobs">Jobs / Careers</a></li>                                    
                    </ul>
                </div>
                <div class="footer-separator" >
                    &nbsp;    
                </div>
                <div class="footer_box signmeup-baby">
                    <h1>Sign up for exclusive offers and the latest news</h1>
                    <div style=" width: 100%;display: inline-block;">
                        <div style="float: right;"><input type="text" name="subscribe-email" id="subscribeEmail" placeholder="Email Address"/><span id="signup-baby-btn">Submit</span></div>
                    </div>
                    
                    <div class="social_link footer-social">
                        <a href="https://www.facebook.com/YourArtGallery" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/facebook.png"  alt="Share to Facebook" /></a>
                        <a href="https://twitter.com/YourArtGallery" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/twitter.png"  alt="Share to Twitter" /></a>
                        <a href="https://instagram.com/Your.Art.Gallery/" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/instagram.png"  alt="Instagram" /></a>
                        <a href="https://www.pinterest.com/yourartgallery/" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/pinterest.png"  alt="Share to Pinterest" /></a>
                        <a href="https://plus.google.com/+Yourartgallery/posts" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/google.png"  alt="Share to Google" /></a>
                        <a href="https://www.linkedin.com/company/your-art-gallery-llc" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/linkedin.png"  alt="Stumble It" /></a>
                        <a href="https://www.youtube.com/YourArtGallery" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/youtube.png"  alt="Share to Youtube" /></a>            
                        <!--<a href="http://yaguniversity.tumblr.com" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/yag_university.png"  alt="YAG University" /></a>-->
                    </div>
                </div>

                <div class="footer_bottom clear clearfix">
                    <span>Your Art Gallery, LLC &copy;2016</span>
                </div>
            </footer>
            <script>        
                var googleAnalyticsId = '<?php echo $this->config('google_analytics_id') ?>';
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                ga('create', googleAnalyticsId, 'auto');
                ga('send', 'pageview');

            </script>
            <script>
                var addthis_config = addthis_config || {};
                addthis_config.data_track_addressbar = false;
                addthis_config.data_track_clickback = false;
            </script>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-537097da2d2591ed"></script>                        

        </div>
</footer>