<footer>                
  <div class="footer-top-container">
    <div class="wrapper">
      <div class="addthis_toolbox">   
        <div class="social_link">

          <a href="https://www.facebook.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/facebook_share.png"  alt="Share to Facebook" /></a>
          <a href="https://twitter.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/twitter_share.png"  alt="Share to Twitter" /></a>
          <a href="https://instagram.com/Your.Art.Gallery/"><img src="<?php echo $this->basePath() ?>/img/instagram_share.png"  alt="Instagram" /></a>
          <a href="https://www.pinterest.com/yourartgallery/"><img src="<?php echo $this->basePath() ?>/img/pinterest_share.png"  alt="Share to Pinterest" /></a>
          <a href="https://plus.google.com"><img src="<?php echo $this->basePath() ?>/img/google_share.png"  alt="Share to Google" /></a>
          <a href="https://www.linkedin.com/company/your-art-gallery-llc"><img src="<?php echo $this->basePath() ?>/img/linkedin_share.png"  alt="Stumble It" /></a>
          <a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $this->basePath() ?>/img/youtube_share.png"  alt="Share to Youtube" /></a>            

        </div>
      </div>
    </div>
    <div class="footer-container">
      <footer class="wrapper clearfix">

        <div class="footer_box">
          <a href="<?php echo $this->config('main_site', 'url') ?>/about-us"><h1>COMPANY INFO</h1></a>
          <ul>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-us">About Us</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-our-prints">About Our Prints</a></li>
            <li><a href="http://yaguniversity.tumblr.com/tagged/media" target="_blank">Media</a></li>
            <li><a href="http://yaguniversity.tumblr.com/tagged/news" target="_blank">News & Press</a></li>
            <li><a href="http://yaguniversity.tumblr.com/tagged/events" target="_blank">Events & Exhibitions</a></li>
          </ul>
        </div>

        <div class="footer_box">
          <a id="loginPopup10" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup" ><h1>ORDER INFO</h1></a>
          <ul>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup">Track An Order</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/shipping-and-returns">Shipping Options</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/shipping-and-returns">Return Information</a></li>
          </ul>
        </div>

        <div class="footer_box">
          <a href="<?php echo $this->config('main_site', 'url') ?>/feedback"><h1>HELP / FEEDBACK</h1></a>
          <ul>
            <li><a href="http://yaguniversity.tumblr.com/faq" target="_blank">FAQs</a></li>
            <li><a href="http://yaguniversity.tumblr.com" target="_blank">YAG University</a></li>
            <li>
              <a href="<?php echo $this->config('main_site', 'url') ?>/feedback">Feedback</a>
            </li>
          </ul>
        </div>

        <div class="footer_box" style="width: 14%;">
          <a href="<?php echo $this->config('main_site', 'url') ?>/our-policies"><h1>TERMS & POLICIES</h1></a>
          <ul>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Sustainability Policy</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Privacy Policy</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Purchasing Policy</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/terms-of-service">Terms & Conditions</a></li>
          </ul>
        </div>

        <div class="footer_box" style="width: 11%;">
          <a href="<?php echo $this->config('main_site', 'url') ?>/contact-us"><h1>CONTACT US</h1></a>
          <ul>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/contact-us">Location / Hours</a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/jobs">Jobs / Careers</a></li>                                    
          </ul>
        </div>
        <div class="footer-separator" >
          &nbsp;    
        </div>
        <div class="footer_box signmeup-baby">
          <h1>Sign up for exclusive offers and the latest news</h1>
          <div style="float: left;">
            <img src="<?php echo $this->basePath() ?>/img/bg-rateing.jpg"/>
          </div>
          <div>
            <div style="float: right;"><input type="text" name="subscribe-email" placeholder="Email Address"/></div>
            <div style="float: right;"><button id="signup-baby-btn">Sign Me Up, Baby!</button></div>
          </div>
        </div>

        <div class="footer_bottom clear clearfix">
          <span>Your Art Gallery &copy;2015</span>
        </div>
      </footer>
      <script>
        var addthis_config = addthis_config || {};
        addthis_config.data_track_addressbar = false;
        addthis_config.data_track_clickback = false;
      </script>
      <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-537097da2d2591ed"></script>                        

    </div>
</footer>