<hr>
<div class="container search-box clear">
    <div>        
        <div class="container contactform center">
            <h2 class="text-center wowload vmin2 fontnew">Stay up to date with news and contests!</h2>  
            <div class="row spacer">
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="subscribe-email" class="form-control" placeholder="ENTER EMAIL ADDRESS">
                        <span class="input-group-btn">
                            <button class="btn btn-default" id="signup-baby-btn" type="button">SUBMIT</button>
                        </span>
                    </div>
                </div>
            </div>                
        </div>
    </div>
</div>
<div class="social col-lg-12 col-lg-offset-3">
    <ul>
        <li><a href="https://www.facebook.com/YourArtGallery"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/facebook.png"></a></li>
        <li><a href="https://twitter.com/YourArtGallery"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/twitter.png"></a></li>
        <li><a href="https://www.pinterest.com/yourartgallery/"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/pinterest.png"></a></li>
        <li><a href="https://instagram.com/Your.Art.Gallery/"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/instagram.png"></a></li>
        <li><a href="https://www.youtube.com/YourArtGallery"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/youtube.png"></a></li>
        <li><a href="https://www.linkedin.com/company/your-art-gallery-llc"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/linkedin.png"></a></li>
        <li><a href="https://plus.google.com/+Yourartgallery/posts"><img src="<?php echo $this->config('main_site', 'url') ?>/assets/themes/yag_mobile/images/google_plus.png"></a></li>        
    </ul>
</div>
<div class="footer-tabs">
    <ul>
        <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-us">About</a></li>
        <li>|</li>
        <li><a href="<?php echo $this->config('main_site', 'url') ?>/faqs" target="_blank">Questions</a></li>
        <li>|</li>
        <li><a href="<?php echo $this->config('main_site', 'url') ?>/terms-of-service">Terms</a></li>
        <li>|</li>
        <li><a href="<?php echo $this->config('main_site', 'url') ?>/feedback">Feedback</a></li>
        <li>|</li>
        <li><a href="<?php echo $this->config('main_site', 'url') ?>/contact-us">Contact</a></li>
    </ul>
</div> 
<p  class="text-center ">Your Art Gallery, LLC &copy;<?php echo date('Y'); ?></p>
<div class="modal fade" id="remoteModal" tabindex="-1" role="dialog" aria-labelledby="remoteModal" data-backdrop="static" data-keyboard="false">                        
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>          
</div>
<script>        
    var googleAnalyticsId = '<?php echo $this->config('google_analytics_id') ?>';
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', googleAnalyticsId, 'auto');
    ga('send', 'pageview');

</script>
<script>
    var addthis_config = addthis_config || {};
    addthis_config.data_track_addressbar = false;
    addthis_config.data_track_clickback = false;
</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-537097da2d2591ed"></script>                        