<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Online Galleries- Your Art Gallery- Buy Sell Share Art &ndash; Your Art Gallery')->setAutoEscape(false) ?>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <?php echo $this->headMeta() ?>
        <meta name="description" content="Your Art Gallery is an easy to use online gallery for artists to share, buy, and sell Fine Art photography. Create your own gallery or browse for your perfect art piece today!">
        <meta name="keywords" content="Art Photography, Photography, Canvas Prints, Fine Art Gallery, eGallery, Image Gallery, Stock Images, Photographic Art, Digital Imaging Photography, Stock Pictures, Create Your Gallery, Online Gallery, Buy Art, Sell My Art, Online Portfolio, Create Your Portfolio, Portfolios">
        <meta name="robots" content="index, follow">
        <link rel="shortcut icon" href="<?php echo $this->basePath('favicon.ico') ?>"/>

        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'theme_assets_path') ?>/css/normalize.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'theme_assets_path') ?>/style.main.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'theme_assets_path') ?>/css/main.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'theme_assets_path') ?>/css/demo.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'theme_assets_path') ?>/css/custom-css.css">    
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'theme_assets_path') ?>/css/validationEngine.jquery.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/css/custom.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/css/square/purple.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->config('main_site', 'url') ?>/assets/css/font-awesome/css/font-awesome.css"> 
        <script>
            var browser = {'mobile': '0', 'iOS': '0'};
            var baseURL = '<?php echo $this->config('main_site', 'url') ?>';
            var gameBasePath = '<?php echo $this->basePath() ?>';
        </script>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/icheck.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/js/jquery.browser.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'url') ?>/assets/javascript/shared.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/js/theme.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'url') ?>/assets/javascript/public.min.js"></script>  
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/js/modernizr.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/js/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/js/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'url') ?>/assets/javascript/custom.js"></script>
        <script type="text/javascript" src="<?php echo $this->config('main_site', 'url') ?>/assets/javascript/login.js"></script>

    </head>
    <body>
        <div id="overlay">&nbsp;</div>
        <div id="workbox"></div>
        <div id="hoverWindow"><div id="hoverWindowInner"></div></div>
        <header class="wrapper clearfix">            
            <div class="home_head_new" >                    
                <div class="home_header_msg ">
                    <?php echo $this->layout()->settings['home_header_text_msg'];?>
                </div>                        
            </div>
            <div class="header-container">
                <div class="wrapper clearfix">                          
                    <div class="header-logo-section pull-left">
                        <h1>
                            <a href="<?php echo $this->config('main_site', 'url') ?>">
                                <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/yag-logo.png" alt="Your Art Gallery" class="h-logo"/>
                            </a>
                        </h1>
                    </div> 
                    <div class="pull-right">
                        <div class="header-cart-section pull-right"> 
                            <form action="<?php echo $this->config('main_site', 'url') ?>/search.php" method="get" id="hsearchForm">
                                <div class="h-sbox pull-left inline-block">
                                    <div>
                                        <span class="font-11 mr-3">
                                            <label><input type="radio" name="searchType" id="hSearchImage" class="radio-button mr-3 v-middle" checked="checked">SEARCH BY IMAGE</label>
                                        </span>                            
                                        <span class="font-11">
                                            <label><input type="radio" name="searchType" id="hSearchArtist" class="radio-button mr-3 v-middle">SEARCH BY ARTIST</label>
                                        </span>                            
                                    </div>
                                    <div class="bg-white">
                                        <input type="text" name="searchPhrase" placeholder="SEARCH ART" class="h-searchbox text-centered"/>
                                        <span class="fa fa-search h-searchbtn" id="hSsearchBtn"></span>
                                    </div>
                                </div>
                            </form>
                            <div class="p-10 h-cbox inline-block pull-right">
                                <div class="h-cart-link">
                                    <a href="<?php echo $this->config('main_site', 'url') ?>/cart.php">CART: <?php if(isset($_SESSION['cartTotalsSession']['itemsInCart'])){ echo $_SESSION['cartTotalsSession']['itemsInCart']; } else { echo '0';} ?> ITEMS(S)</a>
                                </div>                            
                                <?php                       
                                if ($this->session()->mem_id || !empty($this->guestSession()->email)) { 
                                    if ($this->session()->login_as_buyer == 1 && $this->session()->membership == 1) {
                                        $userHomePage = $this->config('main_site', 'url') . '/buyer.welcome.php';
                                    } elseif ($this->session()->membership > 1) {
                                        $userHomePage = $this->config('main_site', 'url') . '/artist.welcome.php';
                                    } else {
                                        $userHomePage = '#';
                                    }

                                    if ($this->session()->username != "") {
                                        $userDisName = $this->session()->username;
                                    } elseif ($this->session()->f_name != "") {
                                        $userDisName = $this->session()->f_name;
                                    } elseif (!empty($this->guestSession()->email)) {
                                        $userDisName = 'Guest';
                                    }
                                    ?>
                                <div class="h-user-sect">
                                    <a href="<?php echo $userHomePage; ?>" class="h-uname show-ellipsis v-middle inline-block"><?php echo $userDisName; ?>,</a>
                                    <a href="<?php echo $this->config('main_site', 'url') ?>/login.php?cmd=logout" class="v-middle inline-block">Logout</a>
                                </div>
                                <?php } else { ?>
                                    <div class="h-login-hld">
                                        <span>
                                            <a href="<?php echo $this->config('main_site', 'url') ?>/create-account" class="font-white">Join Now</a>
                                        </span>
                                        |
                                        <span>
                                            <a id="loginPopup" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=newLoginPopup" class="font-white">Log In</a>
                                        </span>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="clr"></div>
                        <div class="pull-right">
                            <?php echo $this->partial('navigation.phtml'); ?>
                        </div>
                    </div>
                    <div class="clr"></div>
                    <hr class="header-hline">
                </div>
            </div>
        </header>        

        <div class="wrapper flashMessages">
            <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
              &times;
          </button>
          <ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');

            echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
            ?>
        </div>

        <div class="container">
            <div class="main wrapper clearfix">
                <?php echo $this->content; ?>            
            </div>
        </div> <!-- /container -->
        <?php echo $this->partial('footer.phtml'); ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
