<?php $session = $this->session();  ?>
<nav class="nav-others">
    <ul>
        <li class="myaccount-dropmenu">
            <span class="span-anchor">About&nbsp;<span class="dropdown_header">&#8744;</span></span>
            <ul>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-us">About Us</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/about-our-prints">About Our Prints</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/our-policies">Our Policies</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/shipping-and-returns">Shipping &amp; Returns</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/terms-of-service">Terms of Service</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/corporate-sales">Corporate Sales</a></li>                
            </ul>
        </li>
        <li class="myaccount-dropmenu" style="width:130px;">
            <a href="<?php echo $this->config('main_site', 'url') ?>/image-search">Shop&nbsp;<span class="dropdown_header">&#8744;</span></a>
            <ul>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/search.php?mode=best-selling-media&new=1">Best Selling</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/image-search?new=1">Highest Rated</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/search.php?mode=popular-media&new=1">Most Viewed</a></li>
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/search.php?searchSortBy=leditions">Limited Editions</a></li>                
            </ul>
        </li>
        <li class="myaccount-dropmenu" style="width: 160px;">
            <span class="span-anchor">For Artists/ Buyer&nbsp;<span class="dropdown_header">&#8744;</span></span>
            <ul>
                <?php if (!($session->mem_id || !empty($this->guestSession()->email))) { ?>
                    <li><a href="<?php echo $this->config('main_site', 'url') ?>/create-account">Join For Free</a></li>
                <?php }  ?>               
                <li><a href="<?php echo $this->config('main_site', 'url') ?>/sell-your-art">Sell Your Art</a></li>                
                <?php  if ($session->mem_id || !empty($this->guestSession()->email)) { ?>
                    <?php if ($session->login_as_buyer == 1 && $session->membership == 1) { ?>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/create.artist.account.php">My Artist Account</a></li>    
                    <?php } else { ?>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/artist.welcome.php">My Artist Account</a></li>
                    <?php } ?>
                        <li><a href="<?php echo $this->config('main_site', 'url') ?>/buyer.welcome.php">My Buyer Account</a></li>
                <?php } else { ?>
                    <li><a id="loginPopup3" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=newLoginPopup">My Artist Account</a></li>
                    <li><a class="loginPopArtist" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=newLoginPopup&login_redirect=order_history.php">My Buyer Account</a></li>
                <?php } ?>
            </ul>
        </li>
        <li style="margin-left: 50px;width: 110px;"><a href="<?php echo $this->config('main_site', 'url') ?>/contests">Contests</a></li>
        <li class="blog-link"><a href="http://www.yaguniversity.com" target="_blank">Blog</a></li>
    </ul>
</nav>