<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->first, 'size' => $this->itemCountPerPage, 'id' => $this->id, 'action' => $this->action)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'size' => $this->itemCountPerPage, 'id' => $this->id, 'action' => $this->action)); ?>">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url($this->route, array('page' => $page, 'size' => $this->itemCountPerPage, 'id' => $this->id, 'action' => $this->action)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->next, 'size' => $this->itemCountPerPage, 'id' => $this->id, 'action' => $this->action)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array( 'page' => $this->last, 'size' => $this->itemCountPerPage, 'id' => $this->id, 'action' => $this->action)); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>