<div class="col-md-4 contest-buttons ">
    <?php if ($contest['coming_soon'] == 0) {
        if ($contest['voting_started']): ?>
           <button class="btn btn-default" onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/voting/<?php echo $contest['id']; ?>'">Vote Now</button>
       <?php else: ?>
           <button class="btn btn-default vote-soon" style="background-color: #d1d3d4 !important;border: 5px solid #e5da7c;">Vote Soon</button>
       <?php endif;     
    } elseif($contest['coming_soon'] == 1) { ?>
            <button class="btn btn-default" disabled="disabled">Coming Soon</button>   
    <?php } ?>
    <br>
    <button class="btn btn-default"  onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/learn-more'">Learn More</button>
    <br>
    <?php if ($contest['voting_started']): ?>
        <button class="btn btn-default" onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>'">Rankings</button>
    <?php endif; ?>       
    <br>
    <div class="contest-winner">
        <?php if ($contest['coming_soon'] == 0) { ?>
            <?php $percentage = ($contest['total_entries']) ? ($contest['total_entries'] / $contest['max_no_of_photos']) * 100 : 0 ?>
            <img src="<?php echo $this->basePath() ?>/img/closed.png"  alt="contest closed" style="width:40%" />
        <?php } elseif($contest['coming_soon'] == 1) { ?>
           <!--<img src="<?php echo $this->basePath() ?>/img/congratulation.png"  alt="contest closed" style="width:40%" />-->
        <?php } ?>
    </div>
    <br>
    <div class="gold">
        <?php if (isset($contest['entered']) && $contest['entered']): ?>
            Share Your Submission for Votes
        <?php else: ?>
            Share this contest
        <?php endif;?>
    </div>
    <?php echo $this->partial('social_sharing.phtml', array(
        'contest' => $contest, 
        'type' => $type,
        'contestType' => $contestType,
    )); ?>
</div>
