<?php
$this->headMeta()->setProperty('og:title', $contest['name']);
$this->headMeta()->setProperty('og:type', 'website');
if($shareMedia) {
    $this->headMeta()->setProperty('og:image', $this->mediaImage($shareMedia, 'samples'));
    $this->headMeta()->setProperty('og:description', 'I entered the ' . $contest['name'] . ' on YOURARTGALLERY.COM. Check it out now! ');
} else {
    $this->headMeta()->setProperty('og:image', $this->config('aws', 'path') . $contest['thumbnail']);
    $this->headMeta()->setProperty('og:description', $contest['name'] . ' is available on YOURARTGALLERY.COM. Check it out! ' . $this->config('main_site' ,'url') . '/contests');
}
$this->headMeta()->setProperty('twitter:card', 'summary');
$this->headMeta()->setProperty('twitter:site', '@YourArtGallery');
$this->headMeta()->setProperty('twitter:title', $contest['name']);
if($shareMedia) {
    $this->headMeta()->setProperty('twitter:image', $this->mediaImage($shareMedia, 'samples'));
    $this->headMeta()->setProperty('twitter:description', 'I entered the ' . $contest['name'] . ' on YOURARTGALLERY.COM. Check it out now! ');    
} else {
    $this->headMeta()->setProperty('twitter:image', $this->config('aws', 'path') . $contest['thumbnail']);    
    $this->headMeta()->setProperty('twitter:description', $contest['name'] . ' is available on YOURARTGALLERY.COM. Check it out! ' . $this->config('main_site' ,'url') . '/contests');    
}
?>
<style>

    ul li {
        list-style: disc;
    }

    .footer_box ul li {
        list-style: none;
    }

    // font sizes css 
    span .wysiwyg-font-size-fs10 {
        font-size: 10px;
    }
    .wysiwyg-font-size-fs12 {
        font-size: 12px;
    }
    .wysiwyg-font-size-fs14 {
        font-size: 14px;
    }
    .wysiwyg-font-size-fs16 {
        font-size: 16px;
    }
    .wysiwyg-font-size-fs18 {
        font-size: 18px;
    }
    .wysiwyg-font-size-fs20 {
        font-size: 20px;
    }
    .progress-percentage {
        color: #646567;
        font-size: 24px;
        position: absolute;
        display: block;
        width: 100%;
    }
</style>
<script>
    
$(document).ready(function() {
    $('.btnPinIt').click(function() {
        var url = $(this).attr('href');
        var media = "<?php if($shareMedia) {
                echo ($this->mediaImage($shareMedia, 'samples'));
            } else {
                echo ($this->config('aws', 'path') . $contest['thumbnail']);
                }
        ?>";
        var desc = $(this).attr('data-desc');
        window.open("//www.pinterest.com/pin/create/button/"+
        "?url="+url+
        "&media="+media+
        "&description="+desc,"pinIt","toolbar=no, scrollbars=no, resizable=no, top=0, right=0, width=750, height=320");
        return false;
    });
});
</script>

<div class="inner_main clearfix">
    <div class="inner_txt clearfix">
        <h1 class="page-titleHead">Artist Challenge & Contests</h1>
    </div>
</div>
<?php 
$cssClass = '';
                
$today = strtotime(date('Y-m-d'));
$entryEndDate = strtotime($contest['entry_end_date']);        
$percentage = ($contest['total_entries']) ? floor(($contest['total_entries'] / $contest['max_no_of_photos']) * 100) : 0;

if($type !== 'exclusive') {

    if ($contest['voting_started'] || $percentage == 100 || ($entryEndDate < $today))
       $cssClass = 'black-border';
    else
       $cssClass = 'purple-border'; 
}
?>
<div class="contest row <?php echo $cssClass ?>">
<?php
$titleClass = 'contest-title';
if ($this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('action') == 'exclusive-contest') {
    $titleClass = 'contest-title gold';
}
?>
<div class="<?php echo $titleClass; ?>"><?php echo $contest['name']; ?></div>
<div class="col-md-5">

    <div class="contest-description">
        <?php echo $contest['description']; ?>
        <br>
        <div class="contest-dates">
            Enter by: <?php echo date("F jS, Y", strtotime($contest['entry_end_date'])); ?>
            <br>
            Winner Announced: <?php echo date("F jS, Y", strtotime($contest['winners_announce_date'])); ?>
        </div>                
    </div>
</div>        
<div class="contest-image col-md-3">
    <img src="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>"  alt="Contest Photo" />
</div>
<?php
switch ($type) {
    case 'new':
        $partial = 'new_rsidebar.phtml';
        break;
    case 'active':
        $partial = 'active_rsidebar.phtml';
        break;
    case 'past':
        $partial = 'past_rsidebar.phtml';
        break;
    case 'my':
        $partial = 'my_rsidebar.phtml';
        break;
    case 'exclusive':
        $partial = 'exclusive_rsidebar.phtml';
        break;
    case 'default':
        $partial = 'my_rsidebar.phtml';
}

switch ($contest['contest_type']) {
    case 'Photo Contest':
        $contestType = 'photo-contest';
        break;
    case 'Fan Favorite':
        $contestType = 'fan-favorite';
        break;
    case 'default':
        $contestType = 'brackets';
}

echo $this->partial($partial, array(
    'contest' => $contest,
    'type' => $type,
    'contestType' => $contestType,
));
?>
</div>
