<?php
switch ($contest['my_type']) {
  case 'new':
    $partial = 'new_rsidebar.phtml';
    break;
  case 'active':
    $partial = 'active_rsidebar.phtml';
    break;
  case 'past':
    $partial = 'past_rsidebar.phtml';
    break;
}

echo $this->partial($partial, array(
    'contest' => $contest,
    'type' => $type,
    'contestType' => $contestType,
));
?>
<div style="display: none; text-align: center" id="upgradePopUp">
    <div class="popup-another-img">
        <a style="float:right; margin-top: -4%; margin-right: -3%;" onclick="hideUpgradePopUp();" href="#."><img style="height: 16px; width: 16px;" alt="" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/close.button.png" /></a>
        <div style="border:1px solid grey; text-align: center; margin: 5%">
            <p style="font-size: 18px; font-weight: bold; text-align: center; color: #663f8e; font-family: 'franklin_gothic_bookregular'; line-height: 1em;">
                Please Upgrade your account to participate in exclusive contests
            </p>                       
        </div>
        <div class="btn-upload-another-img"><input type="button" onClick="javascript:window.location.href = '<?php echo $this->config('main_site', 'url') ?>/upgrade.account.php'"  value="Upgrade Membership"></div>
    </div>
</div>