<style>
    #thanksPopUpDiv {
        position: fixed;
        background-color: transparent;
        width: 500px;
        height: 330px;
        z-index: 9002;
        padding: 20px;
        margin: 0 0 0 265px;
    }
    .btn-upload-another-img {
        float: none;
    }
    .down-image {
        position: absolute;
        margin: 2%;
        margin-left: -15%;
        border: 4px solid rgb(223, 220, 125);
    }
    .upper-image {
        position: relative;
    }
    .progress-percentage {
        color: #646567;
        font-size: 24px;
        position: absolute;
        display: block;
        width: 100%;
    }

    ul li {
        list-style: disc;
    }

    .footer_box ul li {
        list-style: none;
    }

    // font sizes css 
    span .wysiwyg-font-size-fs10 {
        font-size: 10px;
    }
    .wysiwyg-font-size-fs12 {
        font-size: 12px;
    }
    .wysiwyg-font-size-fs14 {
        font-size: 14px;
    }
    .wysiwyg-font-size-fs16 {
        font-size: 16px;
    }
    .wysiwyg-font-size-fs18 {
        font-size: 18px;
    }
    .wysiwyg-font-size-fs20 {
        font-size: 20px;
    }
</style>
<div  class="home_content clearfix">
    <div class="inner_main clearfix">
        <div class="inner_txt clearfix">
            <h1 class="page-titleHead">Artist Challenge & Contests</h1>
        </div>
    </div>

    <?php $session = $this->session(); ?>
    <div class="navigation clearfix">
        <ul>
            <li><a <?php echo $type == 'new' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/new-contest">New Contests</a></li>
            <li><a <?php echo $type == 'active' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/active-contest">Active Contests</a></li>
            <li><a <?php echo $type == 'past' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/past-contest">Past Contests</a></li>
            <?php if ($session->mem_id): ?>
                <li><a <?php echo $type == 'my' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/my-contest">My Contests</a></li>
                <?php if ($session->membership == 4): ?>
                    <li><a <?php echo $type == 'exclusive' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/exclusive-contest">Exclusive Contests</a></li>
                <?php endif; ?>
            <?php else: ?>
                <li><a id="loginPopup2" <?php echo $type == 'my' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=artist">My Contests</a></li>
                <li><a id="loginPopup5" <?php echo $type == 'my' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=artist">Exclusive Contests</a></li>
            <?php endif; ?> 
        </ul>
    </div>

    <div class="contest-list clearfix">
        <?php if (empty($data)) { ?>
            <br><div class="alert alert-info" role="alert"><?php echo $type == 'my' ? "You have not participated in any contest yet" : "More Contests coming soon!"; ?></div>    
            <?php
        } else {
            foreach ($data as $contest):
                ?>
                <div class="contest row <?php echo ($type !== 'exclusive') ? 'black-border' : '' ?>">
                    <?php
                    $titleClass = 'contest-title';
                    if ($this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('action') == 'exclusive-contest') {
                        $titleClass = 'contest-title gold';
                    }
                    ?>
                    <div class="<?php echo $titleClass; ?>"><?php echo $contest['name']; ?></div>
                    <div class="col-md-5">

                        <div class="contest-description">
                            <?php echo $contest['description']; ?>
                            <br>
                            <div class="contest-dates">
                                Enter by: <?php echo date("F jS, Y", strtotime($contest['entry_end_date'])); ?>
                                <br>
                                Winner Announced: <?php echo date("F jS, Y", strtotime($contest['winners_announce_date'])); ?>
                            </div>                
                        </div>
                    </div>        
                    <div class="contest-image col-md-3">
                        <img src="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>"  alt="Contest Photo" />
                    </div>
                    <?php
                    switch ($type) {
                        case 'new':
                            $partial = 'new_rsidebar.phtml';
                            break;
                        case 'active':
                            $partial = 'active_rsidebar.phtml';
                            break;
                        case 'past':
                            $partial = 'past_rsidebar.phtml';
                            break;
                        case 'my':
                            $partial = 'my_rsidebar.phtml';
                            break;
                        case 'exclusive':
                            $partial = 'exclusive_rsidebar.phtml';
                            break;
                        case 'default':
                            $partial = 'my_rsidebar.phtml';
                    }

                    switch ($contest['contest_type']) {
                        case 'Photo Contest':
                            $contestType = 'photo-contest';
                            break;
                        case 'Fan Favorite':
                            $contestType = 'fan-favorite';
                            break;
                        case 'default':
                            $contestType = 'brackets';
                    }

                    echo $this->partial($partial, array(
                        'contest' => $contest,
                        'type' => $type,
                        'contestType' => $contestType,
                    ));
                    ?>
                </div>
                <?php
            endforeach;
        }
        ?>

    </div>

    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator-slide', array(
        'route' => 'home',
        'routeParams' => array(
            'action' => $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('action')
        ),
        'queryParams' => array(
        )
    ));
    ?>
</div>

<script>
    function showThankYouPopUp(image_source, contest_name) {
        $('.contest-name').html(contest_name);
        $('.down-image').attr('src', image_source);
        $('#thanksPopUpDiv').css('top', ($(window).height() / 2 - 300) + 'px');
        $('#thanksPopUpDiv').css('left', ($(window).width() / 2 - $('#thanksPopUpDiv').width() - 50) + 'px');
        $('#thanksPopUpDiv').show();
        $('div#overlay').css('display', 'block');
        $('div#overlay').css('opacity', '0.47');
        $('div#blanket').css('height', '0');
    }

    function hideThankYouPopUp() {
        $('#thanksPopUpDiv').hide();
        $('div#overlay').css('display', 'none');
    }

</script>