<script type="text/javascript" src="//s7.addthis.com/js/250/addthis_widget.js"></script>
<style>
    #thanksPopUpDiv {
        position: fixed;
        background-color: transparent;
        width: 500px;
        height: 330px;
        z-index: 9002;
        padding: 20px;
        margin: 0 0 0 265px;
    }
    #upgradePopUp {
        position: fixed;
        background-color: transparent;
        width: 650px;
        height: 290px;
        z-index: 9002;
        padding: 20px;
        margin: 0 0 0 265px;
    }
    .btn-upload-another-img {
        float: none;
    }
    .down-image {
        position: absolute;
        margin: 2%;
        margin-left: -15%;
        border: 4px solid rgb(223, 220, 125);
    }
    .upper-image {
        position: relative;
    }
    .progress-percentage {
        color: #646567;
        font-size: 24px;
        position: absolute;
        display: block;
        width: 100%;
    }

    ul li {
        list-style: disc;
    }

    .footer_box ul li {
        list-style: none;
    }

    // font sizes css 
    span .wysiwyg-font-size-fs10 {
        font-size: 10px;
    }
    .wysiwyg-font-size-fs12 {
        font-size: 12px;
    }
    .wysiwyg-font-size-fs14 {
        font-size: 14px;
    }
    .wysiwyg-font-size-fs16 {
        font-size: 16px;
    }
    .wysiwyg-font-size-fs18 {
        font-size: 18px;
    }
    .wysiwyg-font-size-fs20 {
        font-size: 20px;
    }
</style>
<div  class="home_content clearfix">
    <div class="inner_main clearfix">
        <div class="inner_txt clearfix">
            <h1 class="page-titleHead">Artist Challenge & Contests</h1>
        </div>
    </div>

    <?php $session = $this->session(); ?>
    <div class="navigation clearfix">
        <ul>
            <li><a <?php echo $type == 'new' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/new-contest">New Contests</a></li>
            <li><a <?php echo $type == 'active' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/active-contest">Active Contests</a></li>
            <li><a <?php echo $type == 'past' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/past-contest">Past Contests</a></li>
            <?php if ($session->mem_id): ?>
                <li><a <?php echo $type == 'my' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/my-contest">My Contests</a></li>            
                <li><a <?php echo $type == 'exclusive' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->basePath() ?>/exclusive-contest">Exclusive Contests</a></li>                            
            <?php else: ?>
                <li><a id="loginPopup2" <?php echo $type == 'my' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=artist&login_redirect=contests/my-contest">My Contests</a></li>
                <li><a id="loginPopup5" <?php echo $type == 'my' ? 'class="nav_active"' : ""; ?> href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=artist&login_redirect=contests/exclusive-contest">Exclusive Contests</a></li>
            <?php endif; ?> 
        </ul>
    </div>

    <div class="contest-list clearfix">
        <div class=" clearfix"></div>
        <?php if (empty($data)) { ?>
            <br><div class="alert alert-info" role="alert"><?php echo $type == 'my' ? "You have not participated in any contest yet" : "More Contests coming soon!"; ?></div>    
            <?php
        } else {
            foreach ($data as $contest):
                ?>
                <div class="contest row <?php echo ($type !== 'exclusive') ? 'black-border' : '' ?>">
                    <?php
                    $titleClass = 'contest-title';
                    if ($this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('action') == 'exclusive-contest') {
                        $titleClass = 'contest-title gold';
                    }
                    ?>
                    <div class="<?php echo $titleClass; ?>"><?php echo $contest['name']; ?></div>
                    <div class="col-md-5">

                        <div class="contest-description">
                            <?php echo $contest['description']; ?>
                            <br>
                            <div class="contest-dates">
                                <?php 
                                    if($contest['max_no_of_photos'] == $contest['total_entries']) {
                                        $date_details = 'active';
                                    } else {
                                        $date_details = $contest['my_type'];
                                    }   
                                    
                                    if($date_details == 'new') { ?>
                                        <?php if($contest['type_id'] == 3) { ?>
                                            Open Entries End: <?php echo date("F jS, Y", strtotime($contest['entry_end_date'])); ?>
                                            Voting Begins: <?php echo date("F jS, Y", strtotime($contest['voting_start_date'])); ?>
                                            <br>
                                            <div class="bracket-round-dates">
                                                <span <?php echo $contest['current_round'] == '1' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round1'])); ?> - Round One 64</span><br>
                                                <span <?php echo $contest['current_round'] == '2' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round2'])); ?> - Round One 32</span><br>
                                                <span <?php echo $contest['current_round'] == '3' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round3'])); ?> - Sweet 16</span><br>
                                                <span <?php echo $contest['current_round'] == '4' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round4'])); ?> - Elite 8</span><br>
                                                <span <?php echo $contest['current_round'] == '5' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round5'])); ?> - Final 4</span><br>
                                                <span <?php echo $contest['current_round'] == '6' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round6'])); ?> - Championship Round!</span><br>
                                            </div>
                                        <?php } else { ?>
                                            Enter by: <?php echo date("F jS, Y", strtotime($contest['entry_end_date'])); ?>
                                        <?php } ?>
                                        
                                <?php } elseif($date_details == 'active') { ?>
                                             <?php if($contest['type_id'] == 3) { ?>
                                                CURRENTLY IN ROUND:
                                                <br>
                                                <div class="bracket-round-dates">
                                                    <span <?php echo $contest['current_round'] == '1' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round1'])); ?> - Round One 64</span><br>
                                                    <span <?php echo $contest['current_round'] == '2' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round2'])); ?> - Round One 32</span><br>
                                                    <span <?php echo $contest['current_round'] == '3' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round3'])); ?> - Sweet 16</span><br>
                                                    <span <?php echo $contest['current_round'] == '4' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round4'])); ?> - Elite 8</span><br>
                                                    <span <?php echo $contest['current_round'] == '5' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round5'])); ?> - Final 4</span><br>
                                                    <span <?php echo $contest['current_round'] == '6' ? 'class="bracket-current-round"' : ""; ?>><?php echo date("d/m/Y", strtotime($contest['round6'])); ?> - Championship Round!</span><br>
                                                </div>
                                            <?php } ?>
                                    Voting Begins: <?php echo date("F jS, Y", strtotime($contest['voting_start_date'])); ?>
                                <?php } ?>
                                <br>
                                Winner Announced: <?php echo date("F jS, Y", strtotime($contest['winners_announce_date'])); ?>
                            </div>                
                        </div>
                    </div>        
                    <div class="contest-image col-md-3">
                        <img src="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>"  alt="Contest Photo" />
                    </div>
                    <?php
                    switch ($type) {
                        case 'new':
                            $partial = 'new_rsidebar.phtml';
                            break;
                        case 'active':
                            $partial = 'active_rsidebar.phtml';
                            break;
                        case 'past':
                            $partial = 'past_rsidebar.phtml';
                            break;
                        case 'my':
                            $partial = 'my_rsidebar.phtml';
                            break;
                        case 'exclusive':
                            $partial = 'exclusive_rsidebar.phtml';
                            break;
                        case 'default':
                            $partial = 'my_rsidebar.phtml';
                    }

                    switch ($contest['contest_type']) {
                        case 'Photo Contest':
                            $contestType = 'photo-contest';
                            break;
                        case 'Fan Favorite':
                            $contestType = 'fan-favorite';
                            break;
                        case 'Brackets':
                            $contestType = 'brackets';
                        case 'default':
                            $contestType = 'brackets';
                    }

                    echo $this->partial($partial, array(
                        'contest' => $contest,
                        'type' => $type,
                        'contestType' => $contestType,
                    ));
                    ?>
                </div>
                <?php
            endforeach;
        }
        ?>

    </div>

    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator-slide', array(
        'route' => 'home',
        'routeParams' => array(
            'action' => $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParam('action')
        ),
        'queryParams' => array(
        )
    ));
    ?>
</div>
<div style="display: none; text-align: center" id="upgradePopUp">
    <div class="popup-another-img" style="padding: 15px; width: 96%;">
        <a style="float:right; margin-top: -2%; margin-right: -1%;" onclick="hideUpgradePopUp();" href="#."><img style="height: 16px; width: 16px;" alt="" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/close.button.png" /></a>
        <div style=" margin: 2%; width: 100%; margin-top: 5px;">
            <div style=" float: left; width: 67%">                
                <p style="font-size: 18px; color: #6e6e70; font-family: 'franklin_gothic_bookregular'; line-height: 1.3em; width: 100%; margin: 9px 0px;">
                    This contest is available for Platinum members only. Simply upgrade your membership level to enter or take advantage of all membership level contests <a href="<?php echo $this->config('main_site', 'url') ?>/contests" style="color: #6E6E70;">here.</a>
                </p>
                <div class="btn-upload-another-img" style="margin-top: 6px; "><input type="button" onClick="javascript:window.location.href = '<?php echo $this->config('main_site', 'url') ?>/upgrade.account.php'"  value="Upgrade Membership"></div>
            </div>
            <div class="upgrade-account-contest-img" style=" margin: 10px;">
                <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/mesg-img-1.png">
            </div>
        </div>
        
    </div>
</div>

<script>
    function showThankYouPopUp(image_source, contest_name) {
        $('.contest-name').html(contest_name);
        $('.down-image').attr('src', image_source);
        $('#thanksPopUpDiv').css('top', ($(window).height() / 2 - 300) + 'px');
        $('#thanksPopUpDiv').css('left', ($(window).width() / 2 - $('#thanksPopUpDiv').width() - 50) + 'px');
        $('#thanksPopUpDiv').show();
        $('div#overlay').css('display', 'block');
        $('div#overlay').css('opacity', '0.47');
        $('div#blanket').css('height', '0');
    }    
   
    function hideThankYouPopUp() {
        $('#thanksPopUpDiv').hide();
        $('div#overlay').css('display', 'none');
    }
    
    $('.btnPinIt').click(function() {
        var url = $(this).attr('href');
        var media = encodeURIComponent($(this).attr('data-image'));
        var desc = $(this).attr('data-desc');
        window.open("//www.pinterest.com/pin/create/button/"+
        "?url="+url+
        "&media="+media+
        "&description="+desc,"pinIt","toolbar=no, scrollbars=no, resizable=no, top=0, right=0, width=750, height=320");
        return false;
    });
    
    function showUpgradePopUp() {
        $('#upgradePopUp').css('top', ($(window).height() / 2 - 160) + 'px');
        $('#upgradePopUp').css('left', ($(window).width() / 2 - $('#upgradePopUp').width() + 15) + 'px');
        $('#upgradePopUp').show();
        $('div#overlay').css('display', 'block');
        $('div#overlay').css('opacity', '0.47');
        $('div#blanket').css('height', '0');
        
    }
    
    function hideUpgradePopUp() {
        $('#upgradePopUp').hide();
        $('div#overlay').css('display', 'none');
        window.location.href = "<?php echo $this->config('main_site', 'url') ?>/contests";
    }

    <?php if ($type == 'exclusive' && $session->mem_id && $session->membership != 4 && empty($data)): ?>
        showUpgradePopUp();           
    <?php endif; ?>
</script>
