
<div class="col-md-4 contest-buttons ">
  <?php if ($contest['my_type'] == 'new'): ?>
    <button class="btn btn-default">You're In</button>
  <?php elseif ($contest['my_type'] == 'active'): ?>
    <?php if ($contest['voting_started']): ?>
      <button class="btn btn-default" onclick="window.location='<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/voting/<?php echo $contest['id']; ?>'">Vote Now</button>
    <?php else: ?>
      <button class="btn btn-default">Vote Soon</button>
    <?php endif; ?> 
  <?php elseif ($contest['my_type'] == 'past'): ?>
    <button class="btn btn-default" onclick="window.location='<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>'">Winner's Announced</button>                       
  <?php endif; ?> 
  <br>
  <button class="btn btn-default"  onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/learn-more/<?php echo $contest['id']; ?>'">Learn More</button>
  <br>
  <button class="btn btn-default" onclick="window.location='<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>'">Rankings</button>   
  <br>
  <img src="<?php echo $this->basePath() ?>/img/congratulation.png"  alt="contest status" />
  <br>
  <div class="gold">Share this contest</div>
  <?php echo $this->partial('social_sharing.phtml'); ?>
</div>
