<div class="col-md-4 contest-buttons ">
    <?php $session = $this->session(); ?>
    <?php if (isset($contest['entered']) && $contest['entered']): ?>
        <?php
        $media = array();
        $media['media_id'] = $contest['media_id'];
        $media['folder_id'] = $contest['folder_id'];
        ?>
        <button class="btn btn-default" style="background-color: #d1d3d4 !important;border: 5px solid #e5da7c;" onclick="showThankYouPopUp('<?php echo $this->mediaImage($media, 'icons'); ?>', '<?php echo $contest['name']; ?>')">You're In</button>
    <?php elseif ($session->mem_id): ?>
        <?php if ($session->login_as_buyer == 1): ?>
            <button id="loginPopup4" class="btn btn-default" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=artist">Enter Contest</button>
        <?php else: ?>
            <button class="btn btn-default" onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/submission/<?php echo $contest['id']; ?>'">Enter Contest</button>   
        <?php endif; ?> 
    <?php else: ?>
            <a class="loginPopArtist" href="<?php echo $this->config('main_site', 'url') ?>/workbox.php?mode=loginPopup&login_type=artist&login_redirect=contests/<?php echo $contestType; ?>/submission/<?php echo $contest['id']; ?>"><button class="btn btn-default" >Enter Contest</button></a>
    <?php endif; ?> 

    <br>
    <button class="btn btn-default"  onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/learn-more'">Learn More</button>
    <br>
    <br>
    <div class="contest-winner">
        <img src="<?php echo $this->basePath() ?>/img/congratulation.png" style="width:50%" alt="contest status" />
        <?php $percentage = ($contest['total_entries']) ? floor(($contest['total_entries'] / $contest['max_no_of_photos']) * 100) : 0 ?>
        <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?php echo $percentage ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $percentage ?>%"> <span class="progress-percentage"><?php echo $percentage ?><span style="font-size: 20px;">%</span>&nbsp;FULL</span></div>
        </div>
        <br>
        <div class="gold">            
            <?php if (isset($contest['entered']) && $contest['entered']): ?>
                Share Your Submission for Votes
            <?php else: ?>
                Share this contest
            <?php endif;?>
        </div>
         <?php echo $this->partial('social_sharing.phtml', array(
             'contest' => $contest,
             'type' => $type,
             'contestType' => $contestType,
             )); ?>
    </div>

    <div style="display: none;" id="blanket"></div>
    <div style="display: none; text-align: center" id="thanksPopUpDiv">
        <div class="popup-another-img">
            <a style="float:right; margin-top: -5%; margin-right: -4%;" onclick="hideThankYouPopUp();" href="#."><img style="height: 16px; width: 16px;" alt="" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/close.button.png" /></a>
            <div style="border:1px solid grey; text-align: center; margin: 5%">
                <p style="font-size: 40px; font-weight: bold; text-align: center; color: #663f8e; font-family: 'franklin_gothic_bookregular'; line-height: 1em;">Thank You
                    <br>
                    <span style="font-size: 25px;">for entering the</span>
                    <br>
                    <b style="font-size: 25px;" class="contest-name"></b>
                    </p>
                <div>                    
                    <p style="font-size: 18px; font-weight: bold; text-align: center; color: #663f8e; font-family: 'franklin_gothic_bookregular';">Your Entry</p>
                    <div style="margin-top: -10%; margin-bottom: 0%; margin-left: 10%;">
                        <img class="down-image" height="122" width="124" src="" style="margin-left: 10px;">
                        <img class="upper-image" width="177" height="189" src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/man-icon-yag.png">            
                    </div>                        
                </div>
            </div>
            <div class="btn-upload-another-img"><input type="button" onClick="javascript:window.location.href = '<?php echo $this->basePath() ?>/new-contest'"  value="More Contests" style="font-weight: bold;"></div>
        </div>
    </div>
</div>
