
<div class="col-md-4 contest-buttons ">
  <button class="btn btn-default" onclick="window.location='<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>'">Winner's Announced</button>   
  <br>
  <button class="btn btn-default"  onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/learn-more'">Learn More</button>
  <br><br>
  <div class="contest-winner">
      
    <?php if (empty($contest['rank'])):?>
    <img src="<?php echo $this->basePath() ?>/img/closed.png"  alt="contest status" style="width:40%" />
    <?php elseif ($contest['rank'] == 1 && $contest['type_id'] != 3) :?>
    <div class="you_ranked">You Ranked</div>
    <div class="rank">WINNER</div>
    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/trophy.png"  alt="contest status" style="width:40%" />
    <?php elseif ($contest['rank'] >= 2 && $contest['rank'] <= 10 && $contest['type_id'] != 3):?>
    <div class="you_ranked">You Ranked</div>
    <div class="rank">Top 10</div>
    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/trophy.png"  alt="contest status" style="width:40%" />
    <?php elseif ($contest['type_id'] == 3):?>
    <div class="you_ranked">You Ranked</div>
    <div class="rank"><?php echo $contest['barcket_badge']; ?></div>
    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/trophy.png"  alt="contest status" style="width:40%" />
    <?php endif; ?>
  </div>  
  <br>
  
  <div class="gold">
      <?php if (isset($contest['entered']) && $contest['entered']) { ?>
        Share how you did
      <?php } else { ?>
        Share this contest
      <?php } ?>
  </div>
  <?php echo $this->partial('social_sharing.phtml', array(
        'contest' => $contest,
        'type' => $type,
        'contestType' => $contestType,
    )); ?>
</div>
