
<div class="col-md-4 contest-buttons ">
  <button class="btn btn-default" onclick="window.location='<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>'">Winner's Announced</button>   
  <br>
  <button class="btn btn-default"  onclick="window.location = '<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/learn-more/<?php echo $contest['id']; ?>'">Learn More</button>
  <br>
  <button class="btn btn-default" onclick="window.location='<?php echo $this->basePath() ?>/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>'">Rankings</button>   
  <br>
  <img src="<?php echo $this->basePath() ?>/img/congratulation.png"  alt="contest status" />
  <br>
  <div class="gold">Share this contest</div>
  <?php echo $this->partial('social_sharing.phtml'); ?>
</div>
