<?php
$session = $this->session();
if (isset($contest['entered']) && $contest['entered']) {
    $media = array();
    $media['media_id'] = $contest['media_id'];
    $media['folder_id'] = $contest['folder_id'];
}
?>
<div class="social">
    <ul>
        <?php if (($type == "past" || $type == "past-winners") && isset($contest['entered']) && $contest['entered']) { ?>
            <li><a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" title="Faceebook" ><img src="<?php echo $this->basePath() ?>/mobile/images/facebook.png"  alt="Share to Facebook" /></a>
            <li><a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" title="Twitter" addthis:title="The results are in, see how I did in the  <?php echo $contest['name']; ?>"><img src="<?php echo $this->basePath() ?>/mobile/images/twitter.png"  alt="Share to Twitter" /></a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" data-image="<?php echo $this->mediaImage($media, 'icons'); ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/mobile/images/pinterest.png"  alt="Share to Pinterest" /></a>
            <li><a href="https://plusone.google.com/share?url=<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" target="_blank" ><img src="<?php echo $this->basePath() ?>/mobile/images/google_plus.png"  alt="Share to Google" /></a>
        <?php } elseif ($type == "past-winners") { ?>
            <li><a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>" title="Faceebook" ><img src="<?php echo $this->basePath() ?>/mobile/images/facebook.png"  alt="Share to Facebook" /></a>
            <li><a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>" title="Twitter" addthis:title="The results are in! Check out the winners of the <?php echo $contest['name'] ?>"><img src="<?php echo $this->basePath() ?>/mobile/images/twitter.png"  alt="Share to Twitter" /></a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>" data-image="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/mobile/images/pinterest.png"  alt="Share to Pinterest" /></a>
            <li><a href="https://plusone.google.com/share?url=<?php echo $this->config('main_site', 'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>" target="_blank" ><img src="<?php echo $this->basePath() ?>/mobile/images/google_plus.png"  alt="Share to Google" /></a>
        <?php } elseif (!($type == "past" || $type == "past-winners") && isset($contest['entered']) && $contest['entered']) { ?>
            <li><a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>"/><img src="<?php echo $this->basePath() ?>/mobile/images/facebook.png"  alt="Share to Facebook" /></a>
            <li><a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" title="Twitter" addthis:title="I entered the <?php echo $contest['name']; ?> on YOURARTGALLERY.COM. Check it out now! "><img src="<?php echo $this->basePath() ?>/mobile/images/twitter.png"  alt="Share to Twitter" /></a>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" data-image="<?php echo $this->mediaImage($media, 'icons'); ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/mobile/images/pinterest.png"  alt="Share to Pinterest" /></a>
            <li><a href="https://plusone.google.com/share?url=<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" target="_blank" ><img src="<?php echo $this->basePath() ?>/mobile/images/google_plus.png"  alt="Share to Google" /></a>
        <?php } else { ?>        
            <li><a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" title="Faceebook" ><img src="<?php echo $this->basePath() ?>/mobile/images/facebook.png"  alt="Share to Facebook" /></a>
            <li><a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" title="Twitter" addthis:title="<?php echo $contest['name']; ?> is available on YOURARTGALLERY.COM. Check it out! "><img src="<?php echo $this->basePath() ?>/mobile/images/twitter.png"  alt="Share to Twitter" /></a></li>
            <li><a href="<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" data-image="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/mobile/images/pinterest.png"  alt="Share to Pinterest" /></a>
            <li><a href="https://plusone.google.com/share?url=<?php echo $this->config('main_site', 'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" target="_blank" ><img src="<?php echo $this->basePath() ?>/mobile/images/google_plus.png"  alt="Share to Google" /></a>
        <?php } ?>
    </ul>
</div>