<div class="social_link contest-share">
    <?php 
        $session = $this->session();
        $media = array();
        $media['media_id'] = $contest['media_id'];
        $media['folder_id'] = $contest['folder_id'];
    ?>
    <?php if ($type == "past" && isset($contest['entered']) && $contest['entered']) { ?>
        <a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site' ,'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" title="Faceebook" ><img src="<?php echo $this->basePath() ?>/img/facebook_share.png"  alt="Share to Facebook" /></a>
        <a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site' ,'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" title="Twitter" addthis:title="Thanks for your votes in  YOURARTGALLERY.COM <?php echo $contest['name']; ?> Checkout I did"><img src="<?php echo $this->basePath() ?>/img/twitter_share.png"  alt="Share to Twitter" /></a>  
        <a href="<?php echo $this->config('main_site' ,'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" data-image="<?php echo $this->mediaImage($media, 'icons'); ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/img/pinterest_share.png"  alt="Share to Pinterest" /></a>
        <a href="https://plusone.google.com/share?url=<?php echo $this->config('main_site' ,'url') ?>/contests/<?php echo $contestType; ?>/rankings/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id']; ?>" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/google_share.png"  alt="Share to Google" /></a>
    <?php } elseif($type != "past" && isset($contest['entered']) && $contest['entered']) { ?>
        <a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id'];?>"/><img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/facebook.png"  alt="Share to Facebook" /></a>
        <a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id'];?>" title="Twitter" addthis:title="I entered the <?php echo $contest['name']; ?> on YOURARTGALLERY.COM. Check out now "><img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/twitter.png"  alt="Share to Twitter" /></a>
        <a href="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id'];?>" data-image="<?php echo $this->mediaImage($media, 'icons'); ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/img/pinterest_share.png"  alt="Share to Pinterest" /></a>
        <a class="addthis_button_pinterest_share" pi:pinit:url="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>/mid/<?php echo $contest['media_id'];?>" pi:pinit:media="{$auto_crop_image}"><img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/pinterest.png"  alt="Share to Pinterest" /></a>
    <?php } else { ?>        
        <a class="addthis_button_facebook" addthis:url="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" title="Faceebook" ><img src="<?php echo $this->basePath() ?>/img/facebook_share.png"  alt="Share to Facebook" /></a>
        <a class="addthis_button_twitter" addthis:url="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" title="Twitter" addthis:title="<?php echo $contest['name']; ?> is available on YOURARTGALLERY.COM. Enter to win!"><img src="<?php echo $this->basePath() ?>/img/twitter_share.png"  alt="Share to Twitter" /></a>  
        <a href="<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" data-image="<?php echo $this->config('aws', 'path') . $contest['thumbnail']; ?>" data-desc="<?php echo $contest['id']; ?>" class="btnPinIt" ><img src="<?php echo $this->basePath() ?>/img/pinterest_share.png"  alt="Share to Pinterest" /></a>
        <a href="https://plusone.google.com/share?url=<?php echo $this->config('main_site' ,'url') ?>/contests/details/id/<?php echo $contest['id']; ?>" target="_blank" ><img src="<?php echo $this->basePath() ?>/img/google_share.png"  alt="Share to Google" /></a>
    <?php } ?>
</div>
