<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php //echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headTitle('YAG Games Admin Portal'); ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/vendle_icon.ico'))
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/plugins/bootstrap-datepicker/css/datepicker.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/plugins/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/style-metronic.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/themes/default.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/style-responsive.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/style.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/plugins/bootstrap/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/plugins/uniform/css/uniform.default.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/custom.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/plugins.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/css/pages/tasks.css'))
                ->prependStylesheet($this->basePath('/css/custom.css'))
                ->prependStylesheet($this->basePath('/library/metronic/template/assets/plugins/bootstrap-toastr/toastr.min.css'));
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile('http://www.google.com/jsapi')
                ->prependFile($this->basePath('/js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/library/metronic/template/assets/scripts/custom/ui-toastr.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/bootbox/bootbox.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/bootstrap-toastr/toastr.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/uniform/jquery.uniform.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/jquery.cokie.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/jquery.blockui.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/bootstrap/js/bootstrap.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/jquery-migrate-1.2.1.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/excanvas.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/respond.min.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/scripts/core/app.js'))
                ->prependFile($this->basePath('/library/metronic/template/assets/plugins/jquery-1.10.2.min.js'))
        ;
        ?>
    </head>
    <body class="page-header-fixed">

        <div class="header navbar navbar-fixed-top">
            <!-- BEGIN TOP NAVIGATION BAR -->
            <div class="header-inner">
                <!-- BEGIN LOGO -->
                <a class="navbar-brand" href="<?php echo $this->basePath('manager'); ?>">
                    <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="logo" class="img-responsive">
                </a>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <img src="<?php echo $this->basePath('img/menu-toggler.png') ?>" alt="">
                </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN TOP NAVIGATION MENU -->
                <ul class="nav navbar-nav pull-right">
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <li class="dropdown user">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="fa fa-user"></i>
                            <span class="username">
                                Contest Admin
                            </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">	
                            <li>
                                <a href="<?php echo $this->config('admin_main_site', 'url') . '?notice=logged_out' ?>">
                                    <i class="fa fa-key"></i> Log Out
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                </ul>
                <!-- END TOP NAVIGATION MENU -->
            </div>
            <!-- END TOP NAVIGATION BAR -->
        </div>

        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
<!--            <div class="page-sidebar-wrapper">
                <div class="page-sidebar navbar-collapse collapse">
                     BEGIN SIDEBAR MENU 
                    <ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
                        <li class="start ">
                            <a href="<?php echo $this->basePath('manager'); ?>">
                                <i class="fa fa-home"></i>
                                <span class="title">
                                    Dashboard
                                </span>
                            </a>
                        </li>
                    </ul>
                     END SIDEBAR MENU 
                </div>
            </div>-->
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="pagecontent">
                    <?php echo $this->content; ?>  
                </div>
            </div>
            <!-- END CONTENT -->
        </div>


        <div class="footer">
            <div class="footer-inner">
                <p> 2015 &copy; Your Art Gallery </p>
            </div>
            <div class="footer-tools">
                <span class="go-top">
                    <i class="fa fa-angle-up"></i>
                </span>
            </div>
        </div>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
