<style>
    .rate-it-popup .rangetitle1{
        font-family: Arial; 
        font-size: 20px !important; 
        font-weight: bold !important; 
        color: #663f8e !important;
    }
    .brk-rate-it{ top: -50px; }
    .brk-old-round{ top: 100px; }
    .rate-it-image-close{ margin:5px; background-color: #d3d2d2; }
    .brk-thankq-popup{
        border: 1px #D3D2D2 solid;
        width: 400px;
        text-align: center;
        margin-bottom: 3px;
    }
</style>
<script type="text/javascript" src="<?php echo $this->config('main_site', 'url') ?>/assets/javascript/workbox.js"></script>
<script type="text/javascript">
    $('#closeWorkbox').click(function () {
        $('#workbox').removeAttr('style');
        $('#workbox').removeAttr('class');
        $('#workbox').html('');
    });

    var contestId = '<?php echo isset($contestId)?$contestId:0; ?>';
    var round = <?php echo isset($contestData['contestDetails']['current_round'])?$contestData['contestDetails']['current_round']:0; ?>;
    
    
    $(".brk-vote-lt,.brk-vote-rt").each(function (key, elem) {        
        $(elem).find('.voteStar').each(function (key2, elem2) {
            var starValue = 10;

            var mediaID = $(elem).data('media-id'); // Get the media ID these stars are for

            $(elem2).css('cursor', 'pointer') // Assign a pointer cursor to those stars that are active				
                    .mouseover(function () {
                        highlightStarsForPhotoContest(elem, key2);
                    }) // Assign a mouse over on the active stars				
                    .click(function () {
                        // Unbind stars to prevent double clicking
                        $(".voteStar")                                
                                .unbind()
                                .css('cursor', 'default');
                        var comboId = <?php echo isset($contestData['contestDetails']['combo_id'])? $contestData['contestDetails']['combo_id'] : 0; ?>;
                        submitVote(contestId, mediaID, round, comboId);
                    }); // Do the rating when the star is clicked on
        });        
    });
    
    $('div[class^=brk-vote-it-img-]').on('mouseover click', function(e){
        var targetStar = $(this).data('target-star');
        $(targetStar).find('.voteStar').trigger(e.type);        
    });    
   
    function submitVote(contestId, mediaId, round, comboId) {        
        var request = $.ajax({
            url: gameBasePath + '/brackets/vote',
            type: "POST",
            data: {'contestId': contestId, 'mediaId': mediaId, 'round': round, 'comboId' : comboId },
            dataType: 'json',
            beforeSend: function () {
                $("#ajaxBusy").removeClass('hide');
            },
            complete: function () {
                $("#ajaxBusy").addClass('hide');
            }
        });

        request.done(function (msg) {
            if (msg.success) {
                $('p#msg').show().delay(5000).fadeOut('slow', function () {
                    closeWorkbox();
                });

                showNextImagePopup();
            } else {
                alert(msg.message)
            }
        });

        request.fail(function (jqXHR, textStatus) {
            alert("Request failed: " + textStatus);
        });
    }

    function showNextImagePopup() {
        workbox({
            page: gameBasePath + '/brackets/get-next-art?contestId=' + contestId + '&round=' + round,            
        });
        scroll(0, 0);       
    }

    function highlightStarsForPhotoContest(elem, current) {
        $(elem).find('.voteStar').each(function (key, elem2)
        {            
            $(elem2).attr('src', '<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/star.1.png');                        
            $('.voteStar').not(elem2).attr('src', '<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/star.0.png');
            $('div[class^=brk-vote-it-img-]').removeClass('brk-vote-it-img-hover');
            var targetImg = $(elem).data('target-img');
            $(targetImg).addClass('brk-vote-it-img-hover');
        });
    }
</script>

<?php if ($contestData['contestDetails'] && !$noImages) : ?>
    <div class="brk-vote-it-popup">
        <div class="brk-vote-it-wrapper">
            <div>
                <div class="brk-vote-it-img-lt pull-left text-center" data-target-star=".brk-vote-lt">
                    <img class="brk-image" src="<?php echo $this->mediaImage($media1, 'samples', 300); ?>" />
                </div>               
                <div class="brk-vote-it-img-rt pull-right text-center" data-target-star=".brk-vote-rt">
                    <img class="brk-image" src="<?php echo $this->mediaImage($media2, 'samples', 300); ?>" />                    
                    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/close.button.png" id="closeWorkbox" class="brk-closeWorkbox">
                </div>
            </div>                     
        </div>
        <div class="brk-bottom-wrapper col-md-12">
            <div class="col-md-1"></div>
            <div class="col-md-4">
                <div class="brk-vote-lt text-center" data-media-id="<?php echo $media1['media_id'] ?>" data-target-img=".brk-vote-it-img-lt">
                    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/star.0.png" class="voteStar">
                    <p>Artist Name:&nbsp;<?php echo $media1['f_name']; ?></p>
                </div>
            </div>
            <div class="col-md-2 text-center no-padding">
                <div class="rate-it-details">
                    <div class="brk-heading-1">OR</div>
                    <div class="brk-heading-2"><?php echo $contestData['round_name']; ?></div>                    
                    <div class="brk-heading-3"><strong><?php echo $contestData['totalRated'] + 1 ?>/<?php echo $contestData['count'] ?></strong></div>
                    <div class="brk-heading-4"><strong>FACEOFF</strong></div>
                </div>                
            </div>
            <div class="col-md-4">
                <div class="brk-vote-rt text-center" data-media-id="<?php echo isset($media2['media_id']) ? $media2['media_id'] : ""; ?>" data-target-img=".brk-vote-it-img-rt">
                    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/star.0.png" class="voteStar">
                    <p>Artist Name:&nbsp;<?php echo isset($media2['f_name'])?$media2['f_name'] : ""; ?></p>
                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
    <?php elseif($showThankq && $noImages): ?>
    <div class="rate-it-popup brk-old-round">
            <div class="rate-it-image-close" >
                <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/close.button.png" id="closeWorkbox" style=" top: 5px; right: 5px;">
                <div class="col-md-12 text-center" style="margin-top: 10px;">
                    <p class="brk-popup-label-3">
                        Welcome to the "<?php echo $contest['name']?>" tournament, vote now on the top contenders!! 
                    </p>
                </div>
            </div>  
             
        <div class="bottom-wrapper">
            <div class="rate-it-detail" style="font-size: 25px;text-align: center;">                
                <div class="contest" style="border:none; text-align: center;">
                    <button id="get-next-image" onclick="showNextImagePopup()" style=" width: 110px;">Ok</button>            
                </div>      
            </div>
        </div>
    </div>
    <?php else : ?>
    <div class="rate-it-popup brk-rate-it">
        <div class="rate-it-wrapper">
      <!--    <div class="rangetitle1 animalcol"><?php echo $media['contest_name']; ?></div>-->
            <div class="brk-thankq-popup">
                <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/close.button.png" id="closeWorkbox" style=" top: 3px;">
            </div>
            <div class="row" style="border:1px solid grey">
                <span class="col-md-4">
                    <img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/thankyou1.png">
                </span>
                <span class="col-md-8" style="font-size: 25px; text-align: center; line-height: 1.2em; color: #663f8e; font-family: 'franklin_gothic_bookregular';">
                     <p><b>Congratulation, </b><br>
                        you have already voted! <br>
                        <?php if($contest['current_round'] != 6) { ?>
                        Be sure to vote again<br>                        
                        next round.</p>
                        <?php } ?>
                </span>            
            </div>            
            <div class="col-md-12 text-center" style="margin-top: 10px;">
                <?php if($contest['current_round'] != 6) { ?>
                    <p class="brk-popup-label-3">Next round start: <?php $round_number = $contest['current_round']+1; $round = "round" . $round_number; echo date("m/d/Y", strtotime($contest[$round])); ?></p>
                <?php } else { ?>
                    <p class="brk-popup-label-3">Winner announce Date: <?php echo date("m/d/Y", strtotime($contest['winners_announce_date'])); ?></p>
                <?php } ?>
            </div>           
        </div>
        <div class="bottom-wrapper">
            <div class="rate-it-detail" style="font-size: 25px;text-align: center;">
                <p><b>Want to Rate More Art?</b></p>
                <div>
                    <a href="<?php echo $this->config('main_site', 'url') ?>/yag-or-gag"><img src="<?php echo $this->config('main_site', 'theme_assets_path') ?>/images/YAGGAG.PNG" style="-webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.5);-moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.5);box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.5); height: 100px;"></a>
                </div>
                <br>
                OR
                <br>
                <div class="contest" style="border:none; text-align: center">
                    <button onclick="window.location = '<?php echo $this->basePath() ?>/active-contest'">More Contests</button>            
                </div>      
            </div>
        </div>
    </div>    
    <?php endif; ?>
