<div class="banner"> 
    <img src="<?php echo $this->basePath() . '/mobile/images/banners/header-home.jpg' ?>" alt="banner" class="img-responsive">
</div>
<div id="content">
    <div class="top-description">
        <h2 class=" wowload purple_title vmin3">Contest Rules & Regulations</h2>
    </div>
    <div class="wowload">
        <h2>HOW TO ENTER:</h2>
    </div>
    <ul>
        <li>All submissions are online via each contest listing.</li>				
        <li>Upload a new image or select an image from your existing portfolio. Please
            note: You will not be able to upload a new image if you have already used
            all available space in your portfolio, based on your subscription level. In
            this case, consider upgrading your membership or replacing an image from
            your portfolio.</li>
        <li>Once your submission has been completed, you will be directed to a
            confirmation page.</li>
        <li>Only one submission per artist.</li>
    </ul>
    <div class="content-reg">
        <div class="wowload">
            <h2>WHO MAY ENTER:</h2>
        </div>
        <div>Any professional, amateur, enthusiast or student photographic artist
            subscribed and a member of YOUR ART GALLERY.
        </div>

    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>PRIZES:</h2>
        </div>
        <div>All prizes must be redeemed within 30 days from the end of contest
        </div>						
    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>CHAMPION:</h2>
            <small>(In addition to the prizes they win along the way)</small>
        </div>
        <ul>
            <li>$250 Credit towards a YourArtGallery.com purchase (ordered through YAG
                Customer Support)</li>            
            <li>Free 6 Month Platinum Membership (If already a Platinum member your
                next 6 months are free)</li>
        </ul>						
    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>FINAL TWO:</h2>
        </div>
        <ul><li>High Definition Photographic Print up to 12" x 18"</li>
            <li>High Definition Photographic Print Gallery Mounted up to 16" x 20"<br>                                    
                (If you are not purchasing your own images Artist Royalty will still be
                applicable)
            </li>            
        </ul>						
    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>FINAL TWO:</h2>
        </div>
        <ul><li>High Definition Photographic Print up to 12" x 18"<br>                                    
                (If you are not purchasing your own images Artist Royalty will still be
                applicable)
            </li>
            
        </ul>						
    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>ENTRY FEE:</h2>
        </div>
        <div>There is not cost to enter!</div>						
    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>JUDGING:</h2>
        </div>
        <div>Entries will be judged based on the Your Art Gallery rating system, in which
            the rating and voting authority your peers and thousands of YAG visitors
            identify the winning images.</div>						
    </div>
    <div class="content-reg">
        <div class="wowload">
            <h2>CONSENT AGREEMENT:</h2>
        </div>
        <div>Submission of an entry to each contest automatically constitutes the contestant's acceptance of all contest rules and conditions, and affirms the contestant acceptance of being in accordance with the Your Art Gallery LLC, Terms of Service. All applicants and contestants retain full copyright of any image submitted. The use of submitted images comply with the <a class="purplecolor" href="<?php echo $this->config('main_site', 'url') ?>/terms-of-service"><b>Terms of Service</b></a> agreement of Your Art Gallery llC., and <a class="purplecolor" href="<?php echo $this->config('main_site', 'url') ?>/artist.welcome.php"><b>Your Promotion Center</b></a> social media opt-in settings at, <a class="purplecolor" href="<?php echo $this->config('main_site', 'url') ?>/portfolio.php"><b>Edit Your Portfolio</b></a>.
            </br></br>
            Entries not complying with contest rules set forth, or entrance found to be manipulating the votes in any fashion will be disqualified. </br></br>
            if you have questions about the above information or would like to know if your image is eligible, please contact us at <a class="purplecolor" href="mailto:info@yourartgallery.com"><b>info@yourartgallery.com</b></a>.</div>						
    </div>
    <br/>
    <div class="p0 col-md-8 col-lg-8">
        <div class="p0 col-md-8 col-lg-12 contests">
            <a href="<?php echo $this->basePath(); ?>" class="btn btn-primary">RETURN TO CONTESTS</a>
        </div>
    </div>
</div>