<?php
    $this->headMeta()->setProperty('twitter:card', 'summary');
    $this->headMeta()->setProperty('twitter:site', '@YourArtGallery');
    $this->headMeta()->setProperty('twitter:title', $contest['name']);
    
    if($shareMedia) {
        $this->headMeta()->setProperty('twitter:image', $this->mediaImage($shareMedia, 'samples'));
        $this->headMeta()->setProperty('twitter:description', 'Thanks for your votes in  YOURARTGALLERY.COM ' . $contest['name'] . '. Checkout how I did');    
    } else {
        $this->headMeta()->setProperty('twitter:image', $this->config('aws', 'path') . $contest['thumbnail']);    
        $this->headMeta()->setProperty('twitter:description', $contest['name'] . ' is available on YOURARTGALLERY.COM. CHECKOUT NOW! ' . $this->config('main_site' ,'url') . '/contests/details/id/' . $contest['id']);    
    }
    
    $this->headMeta()->setProperty('og:title', $contest['name']);
    $this->headMeta()->setProperty('og:type', 'website');
    if($shareMedia) {
        $this->headMeta()->setProperty('og:image', $this->mediaImage($shareMedia, 'samples'));
        $this->headMeta()->setProperty('og:description', 'Thanks for your votes in  YOURARTGALLERY.COM ' . $contest['name'] . '. Checkout how I did');
    } else {
        $this->headMeta()->setProperty('og:image', $this->config('aws', 'path') . $contest['thumbnail']);
        $this->headMeta()->setProperty('og:description', $contest['name'] . ' is available on YOURARTGALLERY.COM. CHECKOUT NOW! ' . $this->config('main_site' ,'url') . '/contests/details/id/' . $contest['id']);
    }
?>
<style>
    .media-list-title {
        background-color: #e5da7c;
        padding: 10px;
        margin: 15px 0px;
        width: 450px;
        font-size: 22px;
        color: #646567;
    }
    .contest {
        font-family: 'franklin_gothic_bookregular';
        font-weight: bold;
        color: #663f8e; 
    }
    .artist-name , .user-name, .rank {
        text-align: center;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis
    }  
    .bracket-champion{
        padding: 0px;
        margin-top: 80px;
        margin-bottom: 1px;
    }
</style>
<div  class="home_content clearfix">
    <div class="inner_main clearfix">
        <div class="inner_txt clearfix">
            <h1 class="page-titleHead">Artist Challenge & Contests</h1>
        </div>
    </div>

    <div class="contest clearfix" style="border:none">
        <div style=" margin: 2px;margin-bottom: 5px; ">
            What is art? It is your turn to help choose. These talented artist have been selected to show their work and need you to choose your
            favorite image to win! You may only choose one image but can come back each day to vote again. For a list of our other contests
            for Voting for please click here <button onclick="window.location = '<?php echo $this->basePath() ?>/active-contest'">Artist Challenge & Contests</button>
        </div>
        <?php
        $dStart = new DateTime(date("Y-m-d"));
        $dEnd = new DateTime($contest['winners_announce_date']);
        $dDiff = $dStart->diff($dEnd);
        ?>
        <?php if ($dEnd > $dStart): ?>
            <div class="clearfix"> 
                <div class="row">
                    <div class="right col-md-4" >
                        <button style="width: 100%;font-size: 28px;" onclick="window.location = '<?php echo $this->basePath() ?>/brackets/voting/<?php echo $contestId; ?>'">Get to Voting!</button>
                    </div>
                </div>
                <div class="row">
                    <div class="right" style="font-weight: bold;color: #000; padding-right: 12px;">
                        Contest countdown: <?php echo $dDiff->days; ?> days remaining
                    </div>
                </div>
            </div>
            <br>
        <?php endif; ?>
        <div>
            <?php if ($dEnd > $dStart): ?>
                <div class="media-list-title">Current Standings</div>
            <?php else: ?>
                <div class="media-list-title">Final Standings</div>
            <?php endif; ?>
            <div class="col-md-12 col-xs-12 no-margin-padding bracket-round" >
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Starting 64</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Top 32</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Sweet 16</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Elite 8</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Final 4</div>
                <div class="left col-md-2 col-xs-2 no-margin-padding" >Semi-Final</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Final 4</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Elite 8</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Sweet 16</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Top 32</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Starting 64</div>
            </div>
            <div class="left col-md-12 col-xs-12 no-margin-padding height-25"> </div>
            <div class="col-md-12 col-xs-12 no-margin-padding bracket-round" >
                <div class="left col-md-1 col-xs-1 no-margin-padding" >                    
                    <?php for($i=0;$i<16;$i++) {
                        if(isset($comboDetails[1])) {
                            $media1 = $comboDetails[1][$i]['contest_media_id1'];
                            $media2 = $comboDetails[1][$i]['contest_media_id2'];
                            $comboId = $comboDetails[1][$i]['combo_id'];
                        } else {
                            $media1 = 0; 
                            $media2 = 0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round1-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round1 white-border" data-round="1" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '40'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div> 
                        <?php } else { ?>
                        <div class="round1"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round1-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round1 white-border" data-round="1" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '40'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div> 
                        <?php } else { ?>
                        <div class="round1"></div>
                        <?php } ?>                           
                    </div>
                    <?php } ?>
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php   
                        if(isset($comboDetails[2])) {
                            $media1 = $comboDetails[2][0]['contest_media_id1'];
                            $media2 = $comboDetails[2][0]['contest_media_id2'];
                            $comboId = $comboDetails[2][0]['combo_id'];
                        } else {
                            $media1 =0;
                            $media2 =0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-up round2-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round2 round2-first white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '45'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2 round2-first "></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round2 white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '45'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2"></div>
                        <?php } ?>
                    </div>
                    <?php for($i=0;$i<7;$i++) { 
                        if(isset($comboDetails[2])) {
                            $media1 = $comboDetails[2][1+$i]['contest_media_id1'];
                            $media2 = $comboDetails[2][1+$i]['contest_media_id2'];                        
                            $comboId = $comboDetails[2][1+$i]['combo_id'];
                        } else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round2 white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '45'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2"></div>
                        <?php } ?>                           
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round2 white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '45'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2"></div>
                        <?php } ?>                       
                    </div>
                    <?php } ?>                    
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php   
                        if(isset($comboDetails[3])) {
                            $media1 = $comboDetails[3][0]['contest_media_id1'];
                            $media2 = $comboDetails[3][0]['contest_media_id2'];
                            $comboId = $comboDetails[3][0]['combo_id'];
                        } else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-up round3-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round3 round3-first white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3 round3-first"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round3 white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3"></div>
                        <?php } ?>
                    </div>
                    <?php for($i=0;$i<3;$i++) {
                        if(isset($comboDetails[3])) {
                            $media1 = $comboDetails[3][1+$i]['contest_media_id1'];
                            $media2 = $comboDetails[3][1+$i]['contest_media_id2'];  
                            $comboId = $comboDetails[3][1+$i]['combo_id'];
                        }  else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round3 white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round3 white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3"></div>
                        <?php } ?>
                    </div>
                    <?php } ?>                    
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php
                        if(isset($comboDetails[4])) {
                            $media1 = $comboDetails[4][0]['contest_media_id1'];
                            $media2 = $comboDetails[4][0]['contest_media_id2'];
                            $comboId = $comboDetails[4][0]['combo_id'];
                        }  else {
                            $media1 =0;
                            $media2 =0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-up round4-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round4 round4-first white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round4 round4-first"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round4 white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                         <?php } else { ?>
                        <div class="round4"></div>
                        <?php } ?>
                    </div>
                    <?php for($i=0;$i<1;$i++) {
                        if(isset($comboDetails[4])) {
                            $media1 = $comboDetails[4][1+$i]['contest_media_id1'];
                            $media2 = $comboDetails[4][1+$i]['contest_media_id2'];  
                            $comboId = $comboDetails[4][1+$i]['combo_id'];
                        }  else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>                    
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round4 white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                         <?php } else { ?>
                        <div class="round4"></div>
                        <?php } ?>   
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round4 white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                         <?php } else { ?>
                        <div class="round4"></div>
                        <?php } ?>
                    </div>
                    <?php } ?>                     
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php   if(isset($comboDetails[5])) {
                                $media1 = $comboDetails[5][0]['contest_media_id1'];
                                $media2 = $comboDetails[5][0]['contest_media_id2'];
                                $comboId = $comboDetails[5][0]['combo_id'];
                            } else {
                                $media1 = 0;
                                $media2 = 0;
                            }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round5-up round5-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="artist-name round5-first-text violet-text" style="font-size: 12px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $medias[$media1]['username'] ?>" class="violet-text"><?php echo $medias[$media1]['f_name'] ?></a></div>
                        <div class="round5 round5-first-zero white-border" data-round="5" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?> 
                        <div class="round5 round5-first"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round5-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round5 white-border" data-round="5" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <div class="artist-name violet-text" style="font-size: 12px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $medias[$media2]['username'] ?>" class="violet-text"><?php echo $medias[$media2]['f_name'] ?></a></div>
                        <?php } else { ?>
                        <div class="round5"></div>
                        <?php } ?>
                    </div>
                </div>
                
                <div class="left col-md-2 col-xs-2 no-margin-padding" >
                    <?php   if(isset($comboDetails[6])) {
                                $media1 = $comboDetails[6][0]['contest_media_id1'];
                                $media2 = $comboDetails[6][0]['contest_media_id2'];
                                $comboId = $comboDetails[6][0]['combo_id'];
                            } else {
                                $media1 = 0;
                                $media2 = 0;
                            }
                        ?>
                    <div class="col-md-12 col-xs-12 no-margin-padding" >
                        <div class="left col-md-6 col-xs-6 no-margin-padding left-round6-up">
                            <?php if(isset($medias[$media1])){ ?>
                            <div class="artist-name round6-first-text violet-text" style="font-size: 12px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $medias[$media1]['username'] ?>" class="violet-text"><?php echo $medias[$media1]['f_name'] ?></a></div>
                            <div class=" round6 round6-first-zero white-border" data-round="6" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                                <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                            </div>
                            <?php } else { ?> 
                            <div class=" round6 round6-first "></div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="col-md-12 col-xs-12 no-margin-padding round6-center-outer" >
                        <div class="col-md-12 col-xs-12 no-margin-padding">
                            <div class="col-md-12 col-xs-12 bracket-champion">
                                Champion
                            </div>
                            <div class="col-md-12 col-xs-12 round6-center">
                                <?php if(isset($contestWinners[0])){ ?>
                                <div class="col-md-12 col-xs-12 round7 no-margin-padding" data-round="7" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                                    <img mediaid="<?php echo $this->KCrypt()->enc($contestWinners[0]['media_id']) ?>" src="<?php echo $this->mediaImage($contestWinners[0], 'icons', '100'); ?>" title="<?php echo $contestWinners[0]['title'] ?>" alt="<?php echo $contestWinners[0]['title'] ?>" />
                                </div>
                                <?php } else { ?> 
                                <div class="col-md-12 col-xs-12 round7 no-margin-padding"></div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="col-md-12 col-xs-12 no-margin-padding round6-center-text">
                            <?php if(isset($contestWinners[0])){ ?>
                            <b>Total Votes: <?php echo $contestWinners[0]['no_of_votes']; ?></b>
                            <div class="artist-name violet-text" style="font-size: 12px;">Artist Name: <?php echo $contestWinners[0]['f_name']; ?></div>
                            <div class="artist-name violet-text" style="font-size: 12px;">User Name:<a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $contestWinners[0]['username'] ?>" class="violet-text"><?php echo $contestWinners[0]['username']; ?></a></div>
<!--                            Total Votes: 158<br>
                            <span class="violet-text">
                            Artist Name: Matthews Thomas<br>
                            User Name: ThomasPhoto
                            </span>-->
                            <?php } ?>
                        </div>
                    </div>
                    <div class="col-md-12 col-xs-12 no-margin-padding" >
                        <div class="col-md-6 col-xs-6 no-margin-padding" ></div>
                        <div class="left col-md-6 col-xs-6 no-margin-padding right-round6-up">
                            <?php if(isset($medias[$media2])){ ?>
                            <div class="round6 round6-second white-border" data-round="6" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                                <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                            </div>
                            <div class="artist-name violet-text" style="font-size: 12px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $medias[$media2]['username'] ?>" class="violet-text"><?php echo $medias[$media2]['f_name'] ?></a></div>
                            <?php } else { ?>
                            <div class="round6 round6-second "></div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php   if(isset($comboDetails[5])) {
                                $media1 = $comboDetails[5][1]['contest_media_id1'];
                                $media2 = $comboDetails[5][1]['contest_media_id2'];
                                $comboId = $comboDetails[5][1]['combo_id'];
                            } else {
                                $media1 = 0;
                                $media2 = 0;
                            }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round5-up round5-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="artist-name round5-first-text violet-text" style="font-size: 12px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $medias[$media1]['username'] ?>" class="violet-text"><?php echo $medias[$media1]['f_name'] ?></a></div>
                        <div class="round5 round5-first-zero white-border" data-round="5" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?> 
                        <div class="round5 round5-first"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round5-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round5 white-border" data-round="5" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <div class="artist-name violet-text" style="font-size: 12px;"><a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $medias[$media2]['username'] ?>" class="violet-text"><?php echo $medias[$media2]['f_name'] ?></a></div>
                        <?php } else { ?>
                        <div class="round5"></div>
                        <?php } ?>
                    </div>
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php
                        if(isset($comboDetails[4])) {
                            $media1 = $comboDetails[4][2]['contest_media_id1'];
                            $media2 = $comboDetails[4][2]['contest_media_id2'];
                            $comboId = $comboDetails[4][2]['combo_id'];
                        }  else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-up round4-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round4 round4-first white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round4 round4-first"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round4 white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                         <?php } else { ?>
                        <div class="round4"></div>
                        <?php } ?>
                    </div>
                    <?php for($i=0;$i<1;$i++) {
                        if(isset($comboDetails[4])) {
                            $media1 = $comboDetails[4][3+$i]['contest_media_id1'];
                            $media2 = $comboDetails[4][3+$i]['contest_media_id2'];  
                            $comboId = $comboDetails[4][3+$i]['combo_id'];
                        }  else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>                    
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round4 white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                         <?php } else { ?>
                        <div class="round4"></div>
                        <?php } ?>   
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round4 white-border" data-round="4" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                         <?php } else { ?>
                        <div class="round4"></div>
                        <?php } ?>
                    </div>
                    <?php } ?>                    
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php
                        if(isset($comboDetails[3])) {
                            $media1 = $comboDetails[3][4]['contest_media_id1'];
                            $media2 = $comboDetails[3][4]['contest_media_id2'];
                            $comboId = $comboDetails[3][4]['combo_id'];
                        }  else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-up round3-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round3 round3-first white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3 round3-first"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round3 white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3"></div>
                        <?php } ?>
                    </div>
                    <?php for($i=0;$i<3;$i++) {
                        if(isset($comboDetails[3])) {
                            $media1 = $comboDetails[3][5+$i]['contest_media_id1'];
                            $media2 = $comboDetails[3][5+$i]['contest_media_id2'];  
                            $comboId = $comboDetails[3][5+$i]['combo_id'];
                        } else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round3 white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '50'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round3 white-border" data-round="3" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '50'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round3"></div>
                        <?php } ?>
                    </div>
                    <?php } ?>                    
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php
                        if(isset($comboDetails[2])) {
                            $media1 = $comboDetails[2][8]['contest_media_id1'];
                            $media2 = $comboDetails[2][8]['contest_media_id2'];
                            $comboId = $comboDetails[2][8]['combo_id'];
                        } else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-up round2-up-first">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round2 round2-first white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '45'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2 round2-first "></div>
                        <?php } ?>
                    </div>
                    
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round2 white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '45'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2"></div>
                        <?php } ?>
                    </div>
                    <?php for($i=0;$i<7;$i++) {
                        if(isset($comboDetails[2])) {
                            $media1 = $comboDetails[2][9+$i]['contest_media_id1'];
                            $media2 = $comboDetails[2][9+$i]['contest_media_id2'];
                            $comboId = $comboDetails[2][9+$i]['combo_id'];
                        } else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round2 white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '45'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2"></div>
                        <?php } ?>                           
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round2 white-border" data-round="2" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '45'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div>
                        <?php } else { ?>
                        <div class="round2"></div>
                        <?php } ?>                       
                    </div>
                    <?php } ?>                    
                </div>
                
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php for($i=0;$i<16;$i++) {
                        if(isset($comboDetails[1])) {
                            $media1 = $comboDetails[1][16+$i]['contest_media_id1'];
                            $media2 = $comboDetails[1][16+$i]['contest_media_id2'];
                            $comboId = $comboDetails[1][16+$i]['combo_id'];
                        } else {
                            $media1=0;
                            $media2=0;
                        }
                        ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round1-up">
                        <?php if(isset($medias[$media1])){ ?>
                        <div class="round1 white-border" data-round="1" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media1]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media1]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media1], 'icons', '40'); ?>" title="<?php echo $medias[$media1]['title'] ?>" alt="<?php echo $medias[$media1]['title'] ?>" />
                        </div> 
                        <?php } else { ?>
                        <div class="round1"></div>
                        <?php } ?>
                    </div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round1-down">
                        <?php if(isset($medias[$media2])){ ?>
                        <div class="round1 white-border" data-round="1" data-comboId="<?php echo $comboId ?>" data-mediaId="<?php echo $medias[$media2]['media_id']; ?>">
                            <img mediaid="<?php echo $this->KCrypt()->enc($medias[$media2]['media_id']) ?>" src="<?php echo $this->mediaImage($medias[$media2], 'icons', '40'); ?>" title="<?php echo $medias[$media2]['title'] ?>" alt="<?php echo $medias[$media2]['title'] ?>" />
                        </div> 
                        <?php } else { ?>
                        <div class="round1"></div>
                        <?php } ?>                           
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
<script type="text/javascript">
        var contestId = "<?php echo $contestId; ?>";
        $('.white-border').click(function () {
            debugger;
            var mediaId = $(this).data('mediaid');
            var request = $.ajax({
                url: gameBasePath + '/brackets/get-image-url',
                type: "POST",
                data: {'mediaId': mediaId },
                dataType: 'json',
            });
            request.done(function (msg) {
                console.log(msg);
                if (msg.success) {
                   window.location = msg.mediaUrl;
                } else {
                    alert(msg.message)
                }
            });
        });
    </script>