<style>
    .media-art {
        width: 150px;
        height: 150px;
    }
    .media-art img {
        //width: 160px;
        width: 100%;
        height: 100%;
        border: 4px solid rgb(223, 220, 125);
        display: table-cell;
        vertical-align: middle;
        background-color: rgb(214, 216, 216);
    }
    .media-list-title {
        background-color: #C8B64C;
        padding: 2px;
        margin:15px 20px;
        width:200px;
        font-size: 22px;
    }
    .contest {
        font-family: 'franklin_gothic_bookregular';
        font-weight: bold;
        color: #663f8e; 
    }
    #workbox {
        top: 0px !important;
    }
    .artist-name , .user-name, .rank {
        text-align: center;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis
    }
    .voting-page {
        height: 40px;
    }
</style>
<div  class="home_content clearfix">
    <div class="inner_main clearfix">
        <div class="inner_txt clearfix">
            <h1 class="page-titleHead">Artist Challenge & Contests</h1>
        </div>
    </div>

    <div class="contest clearfix" style="border:none">
        <div>What is art? It is your turn to help choose. These talented artist have been selected to show their work and need you to choose your
            favorite image to win! You may only choose one image but can come back each day to vote again. For a list of our other contests
            for Voting for please click here <button onclick="window.location = '<?php echo $this->basePath() ?>/active-contest'">Artist Challenge & Contests</button>
        </div>
        <div class="clearfix"> 
            <div class="right">
                <form id="searchFormTest" action="<?php echo $this->basePath() ?>/photo-contest/voting/<?php echo $contestId; ?>" method="post">
                    <label>Search</label>&nbsp;<input type="text" id="searchPhrase" name="search" value="<?php echo $this->escapeHtmlAttr($search) ?>" placeholder="By Artist's First Name">
                </form>
            </div>
        </div>
        <br>
        <div>
             <div class="col-md-12 col-xs-12 no-margin-padding bracket-round" >
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Starting 64</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Top 32</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Sweet 16</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Elite 8</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Final 4</div>
                <div class="left col-md-2 col-xs-2 no-margin-padding" >Semi-Final</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Final 4</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Elite 8</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Sweet 16</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Top 32</div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >Starting 64</div>
            </div>
            <div class="left col-md-12 col-xs-12 no-margin-padding height-25"> </div>
            <div class="col-md-12 col-xs-12 no-margin-padding bracket-round" >
                <div class="left col-md-1 col-xs-1 no-margin-padding" >                    
                    <?php for($i=0;$i<16;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round1-up"><div class="round1"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round1-down"><div class=" round1"></div></div>
                    <?php } ?>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-up round2-up-first"><div class="round2 round2-first"></div></div>
                    <?php for($i=0;$i<7;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-down"><div class="round2"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-up"><div class="round2"></div></div>
                    <?php } ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round2-down"><div class="round2"></div></div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-up round3-up-first"><div class="round3 round3-first"></div></div>
                    <?php for($i=0;$i<3;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-down"><div class="round3"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-up"><div class="round3"></div></div>
                    <?php } ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round3-down"><div class="round3"></div></div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-up round4-up-first"><div class="round4 round4-first"></div></div>
                    <?php for($i=0;$i<1;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-down"><div class="round4"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-up"><div class="round4"></div></div>
                    <?php } ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round4-down"><div class="round4"></div></div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round5-up round5-up-first"><div class="round5 round5-first"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding left-round5-down"><div class="round5"></div></div>                    
                </div>
                <div class="left col-md-2 col-xs-2 no-margin-padding" >
                    <div class="col-md-12 col-xs-12 no-margin-padding" >
                        <div class="left col-md-6 col-xs-6 no-margin-padding left-round6-up"><div class=" round6 round6-first "></div></div>
                    </div>
                    <div class="col-md-12 col-xs-12 no-margin-padding round6-center-outer" >
                        <div class="col-md-12 col-xs-12 round6-center">
                            
                        </div>
                        <div class="col-md-12 col-xs-12 no-margin-padding round6-center-text">
                            Total Votes: 158<br>
                            <span class="violet-text">
                            Artist Name: Matthews Thomas<br>
                            User Name: ThomasPhoto
                            </span>
                        </div>
                    </div>
                    <div class="col-md-12 col-xs-12 no-margin-padding" >
                        <div class="col-md-6 col-xs-6 no-margin-padding" ></div>
                        <div class="left col-md-6 col-xs-6 no-margin-padding right-round6-up"><div class="round6 round6-second "></div></div>
                    </div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round5-up round5-up-first"><div class="round5 round5-first"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round5-down"><div class="round5"></div></div> 
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-up round4-up-first"><div class="round4 round4-first"></div></div>
                    <?php for($i=0;$i<1;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-down"><div class="round4"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-up"><div class="round4"></div></div>
                    <?php } ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round4-down"><div class="round4"></div></div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-up round3-up-first"><div class="round3 round3-first"></div></div>
                    <?php for($i=0;$i<3;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-down"><div class="round3"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-up"><div class="round3"></div></div>
                    <?php } ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round3-down"><div class="round3"></div></div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-up round2-up-first"><div class="round2 round2-first"></div></div>
                    <?php for($i=0;$i<7;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-down"><div class="round2"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-up"><div class="round2"></div></div>
                    <?php } ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round2-down"><div class="round2"></div></div>
                </div>
                <div class="left col-md-1 col-xs-1 no-margin-padding" >
                    <?php for($i=0;$i<16;$i++) { ?>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round1-up"><div class="round1"></div></div>
                    <div class="left col-md-12 col-xs-12 no-margin-padding right-round1-down"><div class=" round1"></div></div>
                    <?php } ?>
                </div>
            </div>
            <div class="media-list contest-list clearfix">
                <div class="row">
                    <?php foreach ($medias as $key => $media): ?>
                        <?php $i = $key + 1; ?>
                        <div class="col-md-2 col-xs-2">
                            <div class="media-art">
                                <a class="media_image" href="#." data-media_id="<?php echo $media['media_id'] ?>">
                                    <img mediaid="<?php echo $this->KCrypt()->enc($media['media_id']) ?>" src="<?php echo $this->mediaImage($media, 'icons'); ?>" title="<?php echo $media['title'] ?>" alt="<?php echo $media['title'] ?>" />
                                </a> 
                                <div class="artist-name" style="font-size: 13px;">Artist Name: <?php echo $media['f_name'] ?></div>
                                <div class="user-name" style="font-size: 13px;">User Name: <a href="<?php echo $this->config('main_site', 'url') ?>/<?php echo $media['username'] ?>"><?php echo $media['username'] ?></a></div>
                            </div>
                        </div>
                        <?php if ($i != 1 && $i % 5 == 0): ?>
                        </div>
                        <div class="clearfix voting-page"></div>
                        <div class="row">
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
                <div class="clearfix voting-page"></div>
            </div>

        </div>
    </div>

    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'paginator-slide', array(
        'route' => 'photo-contest',
        'routeParams' => array(
            'action' => 'voting',
            'id' => $this->contestId,
            'size' => $this->size
        ),
        'queryParams' => array(
            'search' => $this->search
        )
    ));
    ?>

    <script type="text/javascript">

        $(window).ready(function () {
<?php if (empty($search)) { ?>
                workbox({
                    page: gameBasePath + '/photo-contest/get-next-art?contestId=' + contestId,
                    mini: true
                });
<?php } ?>
            scroll(0, 0);
        });

        var contestId = "<?php echo $contestId; ?>";
        $('.media_image').click(function () {
            workbox({
                page: gameBasePath + '/photo-contest/get-next-art?contestId=' + contestId + '&mediaId=' + $(this).data('media_id'),
                mini: true
            });
            scroll(0, 0);
        });
    </script>